"""Offline export/import transfer tests: real zip roundtrips, stdlib only.

Fixtures are tiny generated bytes in tmpdirs; no model blobs are committed.
"""
from __future__ import annotations

import hashlib
import json
import base64
import os
import shutil
import socket
import stat
import subprocess
import sys
import tempfile
import threading
import unittest
import zipfile
from pathlib import Path
from unittest import mock

REPO = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO / "serve"))

from mlx_omarchy_assistant import transfer  # noqa: E402

PLAT = {"system": "Linux", "machine": "aarch64", "python": "3.11", "chip_arch": "t6021"}
WHEEL = "mlx_core-1.0.0-cp311-cp311-manylinux_2_39_aarch64.whl"
WHEEL_BYTES = b"fake-wheel-payload"


def make_wheel(dest_dir: Path, name: str, version: str, *, requires=(), modules=(),
               entry_points: dict | None = None,
               tags: str = "py3-none-any") -> Path:
    """Build a real installable wheel with METADATA/WHEEL/RECORD (tiny, no blobs)."""
    import base64

    def b64(data: bytes) -> str:
        return base64.urlsafe_b64encode(hashlib.sha256(data).digest()).rstrip(b"=").decode()

    dist = f"{name.replace('-', '_')}-{version}"
    files: dict[str, bytes] = {}
    for mod in modules:
        if isinstance(mod, tuple):
            modname, body = mod
        else:
            modname, body = mod, f"VALUE = '{mod}'\n"
        files[f"{modname}.py"] = body.encode()
    if entry_points:
        files[f"{dist}.dist-info/entry_points.txt"] = (
            "[console_scripts]\n"
            + "".join(f"{script} = {target}\n" for script, target in entry_points.items())
        ).encode()
    meta = f"Metadata-Version: 2.1\nName: {name}\nVersion: {version}\n"
    meta += "".join(f"Requires-Dist: {r}\n" for r in requires)
    files[f"{dist}.dist-info/METADATA"] = meta.encode()
    files[f"{dist}.dist-info/WHEEL"] = (
        f"Wheel-Version: 1.0\nGenerator: test\nRoot-Is-Purelib: true\nTag: {tags}\n"
    ).encode()
    record_name = f"{dist}.dist-info/RECORD"
    record = "".join(
        f"{path},sha256={b64(data)},{len(data)}\n" for path, data in files.items()
    )
    files[record_name] = (record + f"{record_name},,\n").encode()
    dest_dir.mkdir(parents=True, exist_ok=True)
    wheel = dest_dir / f"{name}-{version}-{tags}.whl"
    with zipfile.ZipFile(wheel, "w", zipfile.ZIP_DEFLATED) as zf:
        for path, data in files.items():
            zf.writestr(path, data)
    return wheel


def unpack_wheel(wheel: Path, site: Path) -> None:
    """Unpack a wheel into a fake site-packages (importlib.metadata reads dist-info)."""
    with zipfile.ZipFile(wheel) as zf:
        zf.extractall(site)


def make_site_with_wheels(root: Path, specs) -> tuple[Path, Path]:
    """Wheel fixtures dir + matching unpacked fake site-packages. Returns (fixtures, site).

    Each spec is (name, version, requires) or (name, version, requires, modules).
    """
    fixtures = root / "fixtures"
    site = root / "site"
    for name, version, requires, *rest in specs:
        modules = rest[0] if rest else ()
        unpack_wheel(make_wheel(fixtures, name, version, requires=requires,
                                modules=modules), site)
    return fixtures, site


def make_fake_pip(script_path: Path, fixtures: Path, omit: str = "") -> list:
    """A stub `pip download --no-deps` that copies fixture wheels for requested pins."""
    script_path.write_text(
        "import os, shutil, sys\n"
        "args = sys.argv[1:]\n"
        "dest = args[args.index('-d') + 1]\n"
        f"fixtures = {str(fixtures)!r}\n"
        f"omit = {omit!r}\n"
        "pins = [a for a in args if '==' in a]\n"
        "for pin in pins:\n"
        "    if omit and pin.startswith(omit):\n"
        "        continue\n"
        "    name = pin.split('==')[0]\n"
        "    for f in os.listdir(fixtures):\n"
        "        if f.startswith(name + '-'):\n"
        "            shutil.copy(os.path.join(fixtures, f), dest)\n"
        "if omit:\n"
        "    sys.stderr.write('ERROR: No matching distribution for ' + omit + '\\n')\n"
        "    raise SystemExit(1)\n"
    )
    return [sys.executable, str(script_path)]


class Base(unittest.TestCase):
    def setUp(self) -> None:
        self._tmp = tempfile.TemporaryDirectory()
        self.addCleanup(self._tmp.cleanup)
        self.root = Path(self._tmp.name)
        self.src_home = self.root / "src-home"
        self.dst_home = self.root / "dst-home"
        self.chat_dir = self._model_dir(
            "chat", {"model.safetensors": b"Q" * 4096, "config.json": b"{}", "tokenizer.json": b"[]"}
        )
        self.decision_dir = self._model_dir("decision", {"model.safetensors": b"L" * 2048})
        self.wh = self.root / "wheelhouse"
        self.wh.mkdir()
        (self.wh / WHEEL).write_bytes(WHEEL_BYTES)
        self.lock = {
            "version": 1,
            "pair_id": "everyday",
            "routing_policy": "1",
            "context_tokens": 8192,
            "max_questions": 8,
            "created_at": "2026-09-27T00:00:00+00:00",
            "boot_id": None,
            "started_offline": True,
            "chip": {"arch": ["t6021"]},
            "licenses": {"qwen3.8-2b-4bit": "apache-2.0", "laya-mlx": "apache-2.0"},
            "models": {
                "chat": {
                    "id": "qwen3.8-2b-4bit", "repo": "org/qwen", "revision": "a" * 40,
                    "path": str(self.chat_dir), "weights_bytes": 4096, "kv_bytes_per_token": 128,
                },
                "decision": {
                    "id": "laya-mlx", "repo": "convaiinnovations/laya", "revision": "b" * 40,
                    "path": str(self.decision_dir), "weights_bytes": 2048, "kv_bytes_per_token": 0,
                },
            },
        }
        self.pairs = [{"pair_id": "everyday", "lock": self.lock}]

    def _voice_dir(self, *, corrupt: bool = False) -> Path:
        files = {
            "model.safetensors": b"V" * 4096,
            "config.json": b"{}",
            "speech_tokenizer/model.safetensors": b"T" * 1024,
        }
        pack = self.src_home / "voice" / "qwen3-tts-0.6b-customvoice-4bit"
        for rel, data in files.items():
            path = pack / rel
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_bytes(corrupt and rel.endswith("safetensors") and data + b"x" or data)
        manifest = {
            "pack_id": "qwen3-tts-0.6b-customvoice-4bit",
            "repo": "mlx-community/Qwen3-TTS",
            "revision": "c" * 40,
            "license": "apache-2.0",
            "files": {rel: {"bytes": len(d), "sha256": hashlib.sha256(d).hexdigest()}
                      for rel, d in files.items()},
        }
        (pack / "manifest.json").write_text(json.dumps(manifest, indent=1))
        return pack

    def _model_dir(self, role: str, files: dict) -> Path:
        d = self.src_home / "artifacts" / role
        d.mkdir(parents=True)
        for name, data in files.items():
            (d / name).write_bytes(data)
        return d

    def export(self, *, pairs=None, required=(WHEEL,), approved=frozenset({"apache-2.0"}),
               out="bundle.zip", platform=None, voice=(), **kw) -> dict:
        wheels = {}
        for w in required:
            path = self.wh / w
            entry = {"wheel": w, "version": "1.0.0"}
            if path.is_file():
                entry["sha256"] = hashlib.sha256(path.read_bytes()).hexdigest()
                entry["size"] = path.stat().st_size
            wheels[w.split("-")[0].replace("_", "-").lower()] = entry
        return transfer.export_bundle(
            self.root / out,
            pairs=self.pairs if pairs is None else pairs,
            wheelhouse=self.wh,
            wheels=wheels,
            voice=list(voice),
            approved_licenses=set(approved),
            platform_info=dict(platform or PLAT),
            **kw,
        )

    def bundle_path(self, name="bundle.zip") -> Path:
        return self.root / name

    def import_(self, *, approved=frozenset({"apache-2.0"}), bundle="bundle.zip", **kw) -> dict:
        return transfer.import_bundle(
            self.dst_home, self.bundle_path(bundle), set(approved), platform_info=dict(PLAT), **kw
        )

    def rewrite_zip(self, src: Path, dst: Path, mutate) -> None:
        with zipfile.ZipFile(src) as zin, zipfile.ZipFile(dst, "w", zipfile.ZIP_STORED) as zout:
            for zi in zin.infolist():
                zout.writestr(zi.filename, mutate(zi.filename, zin.read(zi.filename)))

    def raw_zip(self, dst: Path, members, external_attrs=None) -> None:
        with zipfile.ZipFile(dst, "w", zipfile.ZIP_STORED) as zf:
            for name, data in members:
                zi = zipfile.ZipInfo(name)
                zi.external_attr = (external_attrs or {}).get(
                    name, (stat.S_IFREG | 0o644) << 16)
                zf.writestr(zi, data)


class ExportImportRoundtrip(Base):
    def test_roundtrip_restores_artifacts_and_localizes_lock(self) -> None:
        manifest = self.export()
        self.assertTrue(manifest["wheels_complete"])
        result = self.import_()
        imports = self.dst_home / "assistant" / "imports"
        chat = imports / "everyday" / "chat"
        for name, data in [("model.safetensors", b"Q" * 4096), ("config.json", b"{}"),
                           ("tokenizer.json", b"[]")]:
            self.assertEqual((chat / name).read_bytes(), data)
        self.assertEqual(
            (imports / "everyday" / "decision" / "model.safetensors").read_bytes(), b"L" * 2048
        )
        self.assertEqual((imports / "wheels" / WHEEL).read_bytes(), WHEEL_BYTES)
        localized = json.loads((imports / "everyday" / "transfer-lock.json").read_text())
        self.assertEqual(localized["models"]["chat"]["path"], str(chat))
        self.assertEqual(localized["models"]["chat"]["revision"], "a" * 40)
        self.assertEqual(localized["models"]["decision"]["path"],
                         str(imports / "everyday" / "decision"))
        self.assertEqual(localized["licenses"], self.lock["licenses"])
        self.assertEqual(localized["chip"], self.lock["chip"])
        receipt = json.loads((imports / "everyday" / "transfer-receipt.json").read_text())
        self.assertEqual(receipt["bundle_id"], manifest["bundle_id"])
        # staging is cleaned up; source lock untouched
        self.assertFalse((self.dst_home / "transfer" / "staging").exists())
        self.assertFalse(list(self.root.glob("bundle.zip.tmp")))

    def test_manifest_hashes_match_payload(self) -> None:
        manifest = self.export()
        self.assertEqual(manifest["format"], transfer.TRANSFER_FORMAT)
        with zipfile.ZipFile(self.bundle_path()) as zf:
            self.assertEqual(
                set(zf.namelist()), set(manifest["files"]) | {transfer.MANIFEST_NAME}
            )
            for rel, entry in manifest["files"].items():
                data = zf.read(rel)
                self.assertEqual(len(data), entry["size"])
                self.assertEqual(hashlib.sha256(data).hexdigest(), entry["sha256"])
        self.assertEqual(manifest["total_bytes"], sum(e["size"] for e in manifest["files"].values()))

    def test_inspect_reports_licenses_without_extraction(self) -> None:
        self.export()
        info = transfer.inspect_bundle(self.bundle_path())
        self.assertEqual(info["bundle_id"], manifest_bundle_id(self.bundle_path()))
        self.assertEqual(info["licenses"], ["apache-2.0"])
        self.assertEqual(info["license_details"],
                         {"apache-2.0": {"models": ["laya-mlx", "qwen3.8-2b-4bit"],
                                         "bytes": 4096 + 2 + 2 + 2048}})
        self.assertEqual(info["pairs"][0]["arch"], ["t6021"])
        self.assertTrue(info["wheels_complete"])
        self.assertEqual(info["platform"]["machine"], "aarch64")

    def test_export_requires_pair_lock(self) -> None:
        with self.assertRaisesRegex(transfer.TransferError, "pair lock"):
            transfer.pair_from_home(self.dst_home, "everyday")

    def test_invalid_lock_named(self) -> None:
        bad = dict(self.lock)
        del bad["licenses"]
        with self.assertRaisesRegex(transfer.TransferError, "licenses"):
            self.export(pairs=[{"pair_id": "everyday", "lock": bad}])
        self.lock["models"]["decision"]["path"] = str(self.root / "missing-dir")
        with self.assertRaisesRegex(transfer.TransferError, "missing-dir"):
            self.export()


class StagedReplacement(Base):
    def test_verified_replacement_and_failure_keeps_old_install(self) -> None:
        self.export(out="a.zip")
        self.import_(bundle="a.zip")
        good = (self.dst_home / "assistant" / "imports" / "everyday" / "chat" / "config.json"
                ).read_bytes()
        # second, different verified bundle replaces it
        (self.chat_dir / "config.json").write_bytes('{"v":2}'.encode())
        self.export(out="b.zip")
        self.import_(bundle="b.zip")
        self.assertEqual(
            (self.dst_home / "assistant" / "imports" / "everyday" / "chat" / "config.json"
             ).read_bytes(), b'{"v":2}')
        # corrupt bundle fails verification and leaves b installed untouched
        self.rewrite_zip(self.bundle_path("b.zip"), self.bundle_path("bad.zip"),
                         lambda n, d: d[:-1] + bytes([d[-1] ^ 0xFF])
                         if n.endswith("chat/config.json") else d)
        with self.assertRaises(transfer.VerificationFailed):
            self.import_(bundle="bad.zip")
        self.assertEqual(
            (self.dst_home / "assistant" / "imports" / "everyday" / "chat" / "config.json"
             ).read_bytes(), b'{"v":2}')
        self.assertEqual(good, b"{}")
        self.assertFalse((self.dst_home / "transfer" / "backup").exists())
        self.assertFalse((self.dst_home / "transfer" / "staging").exists())

    def test_reimport_over_existing_creates_swap(self) -> None:
        self.export(out="a.zip")
        first = self.import_(bundle="a.zip")
        second = self.import_(bundle="a.zip")
        self.assertEqual(first["bundle_id"], second["bundle_id"])
        self.assertTrue(
            (self.dst_home / "assistant" / "imports" / "everyday" / "transfer-lock.json").exists()
        )


class UnsafeArchives(Base):
    def _assert_refused(self, bundle: Path, exc=transfer.UnsafeArchive) -> None:
        with self.assertRaises(exc):
            self.import_(bundle=bundle.name)
        self.assertFalse((self.dst_home / "assistant").exists())
        self.assertFalse((self.dst_home / "transfer").exists())

    def build_payload(self) -> dict:
        manifest = self.export()
        with zipfile.ZipFile(self.bundle_path()) as zf:
            return {n: zf.read(n) for n in zf.namelist()}

    def test_traversal_and_absolute_members(self) -> None:
        members = self.build_payload()
        for evil in ("../evil.txt", "/abs/evil.txt", "a/../../evil", r"back\\slash"):
            m = dict(members)
            m[evil] = b"x"
            self.raw_zip(self.bundle_path("evil.zip"), sorted(m.items()))
            self._assert_refused(self.bundle_path("evil.zip"))

    def test_symlink_and_directory_members(self) -> None:
        members = self.build_payload()
        m = dict(members)
        m["everyday/link"] = b"payload"
        self.raw_zip(self.bundle_path("sym.zip"), sorted(m.items()),
                     external_attrs={"everyday/link": (stat.S_IFLNK | 0o644) << 16})
        self._assert_refused(self.bundle_path("sym.zip"))
        m2 = {k: v for k, v in members.items()}
        self.raw_zip(self.bundle_path("dir.zip"), sorted(m2.items()) + [("everyday/dir/", b"")])
        self._assert_refused(self.bundle_path("dir.zip"))

    def test_duplicate_members(self) -> None:
        members = sorted(self.build_payload().items())
        with zipfile.ZipFile(self.bundle_path("dup.zip"), "w", zipfile.ZIP_STORED) as zf:
            for name, data in members + members[-1:]:
                zf.writestr(name, data)
        self._assert_refused(self.bundle_path("dup.zip"))

    def test_member_not_in_manifest_and_size_mismatch(self) -> None:
        members = self.build_payload()
        m = dict(members)
        m["everyday/extra.bin"] = b"sneaky"
        self.raw_zip(self.bundle_path("extra.zip"), sorted(m.items()))
        self._assert_refused(self.bundle_path("extra.zip"))
        # declared size inconsistent with actual member
        m = dict(members)
        victim = "everyday/chat/config.json"
        m[victim] = b"{}" + b"x" * 10
        self.raw_zip(self.bundle_path("size.zip"), sorted(m.items()))
        self._assert_refused(self.bundle_path("size.zip"))

    def test_hash_mismatch(self) -> None:
        manifest = self.export()
        with zipfile.ZipFile(self.bundle_path()) as zf:
            mb = json.loads(zf.read(transfer.MANIFEST_NAME))
        mb["files"]["everyday/chat/config.json"]["sha256"] = "0" * 64
        members = self.build_payload()
        members[transfer.MANIFEST_NAME] = json.dumps(mb).encode()
        self.raw_zip(self.bundle_path("hash.zip"), sorted(members.items()))
        self._assert_refused(self.bundle_path("hash.zip"), transfer.VerificationFailed)

    def test_bomb_total_cap(self) -> None:
        self.export()
        with self.assertRaises(transfer.UnsafeArchive):
            self.import_(max_total_bytes=1024)


class PlatformAndLicense(Base):
    def test_system_python_machine_mismatch(self) -> None:
        self.export()
        for plat in ({"system": "Darwin", "machine": "aarch64", "python": "3.11",
                      "chip_arch": "t6021"},
                     {"system": "Linux", "machine": "x86_64", "python": "3.11",
                      "chip_arch": "t6021"},
                     {"system": "Linux", "machine": "aarch64", "python": "3.12",
                      "chip_arch": "t6021"}):
            with self.assertRaises(transfer.PlatformMismatch):
                transfer.import_bundle(self.dst_home, self.bundle_path(), {"apache-2.0"},
                                       platform_info=plat)

    def test_chip_mismatch_and_unknown_chip(self) -> None:
        self.export()
        with self.assertRaisesRegex(transfer.PlatformMismatch, "t8103"):
            transfer.import_bundle(self.dst_home, self.bundle_path(), {"apache-2.0"},
                                   platform_info={**PLAT, "chip_arch": "t8103"})
        with self.assertRaisesRegex(transfer.PlatformMismatch, "determine"):
            transfer.import_bundle(self.dst_home, self.bundle_path(), {"apache-2.0"},
                                   platform_info={**PLAT, "chip_arch": None})

    def test_wheel_platform_tag_mismatch_at_export(self) -> None:
        with self.assertRaisesRegex(transfer.PlatformMismatch, WHEEL):
            self.export(platform={**PLAT, "machine": "x86_64"})

    def test_export_requires_license_approval(self) -> None:
        with self.assertRaises(transfer.LicenseNotApproved):
            self.export(approved=set())
        self.assertFalse(self.bundle_path().exists())
        self.lock["licenses"]["laya-mlx"] = "cc-by-nc-4.0"
        with self.assertRaisesRegex(transfer.LicenseNotApproved, "cc-by-nc-4.0"):
            self.export(approved={"apache-2.0"})
        self.export(approved={"apache-2.0", "cc-by-nc-4.0"})

    def test_import_requires_license_approval(self) -> None:
        self.lock["licenses"]["laya-mlx"] = "cc-by-nc-4.0"
        self.export(approved={"apache-2.0", "cc-by-nc-4.0"})
        with self.assertRaisesRegex(transfer.LicenseNotApproved, "cc-by-nc-4.0"):
            self.import_(approved={"apache-2.0"})
        self.assertFalse((self.dst_home / "assistant").exists())
        self.import_(approved={"apache-2.0", "cc-by-nc-4.0"})
        self.assertTrue((self.dst_home / "assistant" / "imports" / "everyday").exists())


class Wheelhouse(Base):
    def test_missing_prepared_wheel_names_exact_file(self) -> None:
        with self.assertRaisesRegex(transfer.WheelhouseIncomplete,
                                    "transformers-4.57.0-py3-none-any.whl"):
            self.export(required=[WHEEL, "transformers-4.57.0-py3-none-any.whl"])
        self.assertFalse(self.bundle_path().exists())

    def test_incomplete_export_is_never_portable(self) -> None:
        required = [WHEEL, "transformers-4.57.0-py3-none-any.whl"]
        manifest = self.export(required=required, allow_incomplete=True)
        self.assertFalse(manifest["wheels_complete"])
        with self.assertRaisesRegex(transfer.TransferError, "not portable"):
            self.import_()


class RuntimeWheelhouse(unittest.TestCase):
    def setUp(self) -> None:
        self._tmp = tempfile.TemporaryDirectory()
        self.addCleanup(self._tmp.cleanup)
        self.root = Path(self._tmp.name)
        self.site = self.root / "site-packages"
        self.fixtures = self.root / "fixtures"
        make_wheel(self.fixtures, "pkga", "1.0.0")
        make_wheel(self.fixtures, "pkgb", "1.0.0", requires=("pkga==1.0.0",))
        unpack_wheel(make_wheel(self.fixtures, "pkga", "1.0.0"), self.site)
        unpack_wheel(make_wheel(self.fixtures, "pkgb", "1.0.0", requires=("pkga==1.0.0",)),
                     self.site)

    def test_closure_follows_installed_requires(self) -> None:
        closure = transfer.runtime_closure(["pkgb"], site_path=self.site)
        self.assertEqual(closure, {"pkga": "1.0.0", "pkgb": "1.0.0"})

    def test_closure_compares_python_versions_numerically(self) -> None:
        unpack_wheel(make_wheel(self.fixtures, "versioned", "1.0.0",
                     requires=('pkga; python_version >= "3.9"',)), self.site)
        self.assertEqual(transfer.runtime_closure(["versioned"], site_path=self.site),
                         {"pkga": "1.0.0", "versioned": "1.0.0"})

    def test_closure_refuses_missing_required_dependency(self) -> None:
        unpack_wheel(make_wheel(self.fixtures, "broken", "1.0.0",
                     requires=("missing-package>=1",)), self.site)
        with self.assertRaisesRegex(transfer.TransferError, "missing-package"):
            transfer.runtime_closure(["broken"], site_path=self.site)

    def test_closure_includes_requested_extras(self) -> None:
        unpack_wheel(make_wheel(self.fixtures, "extra-package", "1.0.0",
                     requires=('pkga; extra == "voice"',)), self.site)
        unpack_wheel(make_wheel(self.fixtures, "consumer", "1.0.0",
                     requires=("extra-package[voice]",)), self.site)
        self.assertEqual(transfer.runtime_closure(["consumer"], site_path=self.site),
                         {"consumer": "1.0.0", "extra-package": "1.0.0", "pkga": "1.0.0"})

    def test_closure_uses_current_environment_by_default(self) -> None:
        sys.path.insert(0, str(self.site))
        try:
            self.assertEqual(transfer.runtime_closure(["pkgb"]),
                             {"pkga": "1.0.0", "pkgb": "1.0.0"})
        finally:
            sys.path.remove(str(self.site))

    def test_closure_skips_other_platform_markers(self) -> None:
        make_wheel(self.fixtures, "pkgc", "2.0.0",
                   requires=('pywin32; sys_platform == "win32"', "pkga>=1.0"))
        unpack_wheel(make_wheel(self.fixtures, "pkgc", "2.0.0",
                                requires=('pywin32; sys_platform == "win32"', "pkga>=1.0")),
                     self.site)
        closure = transfer.runtime_closure(["pkgc"], site_path=self.site)
        self.assertNotIn("pywin32", closure)
        self.assertIn("pkga", closure)

    def test_optional_roots_included_only_when_installed(self) -> None:
        closure = transfer.runtime_closure(["pkgb"], site_path=self.site,
                                           optional_roots=["ghost-dist"])
        self.assertEqual(closure, {"pkga": "1.0.0", "pkgb": "1.0.0"})
        unpack_wheel(make_wheel(self.fixtures, "voice-pkg", "0.5.6"), self.site)
        closure = transfer.runtime_closure(["pkgb"], site_path=self.site,
                                           optional_roots=["voice-pkg"])
        self.assertEqual(closure["voice-pkg"], "0.5.6")

    def test_closure_names_missing_root(self) -> None:
        with self.assertRaisesRegex(transfer.TransferError, "nope"):
            transfer.runtime_closure(["nope"], site_path=self.site)

    def _fake_pip(self, omit: str = "") -> list:
        script = self.root / "fakepip.py"
        script.write_text(
            "import os, shutil, sys\n"
            "args = sys.argv[1:]\n"
            "dest = args[args.index('-d') + 1]\n"
            f"fixtures = {str(self.fixtures)!r}\n"
            f"omit = {omit!r}\n"
            "pins = [a for a in args if '==' in a]\n"
            "for pin in pins:\n"
            "    if omit and pin.startswith(omit):\n"
            "        continue\n"
            "    name = pin.split('==')[0]\n"
            "    for f in os.listdir(fixtures):\n"
            "        if f.startswith(name + '-'):\n"
            "            shutil.copy(os.path.join(fixtures, f), dest)\n"
            "if omit:\n"
            "    sys.stderr.write('ERROR: No matching distribution for ' + omit + '\\n')\n"
            "    raise SystemExit(1)\n"
        )
        return [sys.executable, str(script)]

    def test_prepare_captures_pinned_closure(self) -> None:
        out = self.root / "wheelhouse-out"
        result = transfer.prepare_wheelhouse(
            out, roots=["pkgb"], site_path=self.site, pip=self._fake_pip()
        )
        self.assertEqual(set(result["wheels"]), {"pkga", "pkgb"})
        self.assertEqual(result["pins"], ["pkga==1.0.0", "pkgb==1.0.0"])
        for name, entry in result["wheels"].items():
            data = (out / entry["wheel"]).read_bytes()
            self.assertEqual(hashlib.sha256(data).hexdigest(), entry["sha256"])
            self.assertIn(name, entry["wheel"])

    def test_prepare_names_exact_missing_wheel(self) -> None:
        out = self.root / "wh2"
        with self.assertRaisesRegex(transfer.WheelhouseIncomplete, "pkga==1.0.0") as cm:
            transfer.prepare_wheelhouse(
                out, roots=["pkgb"], site_path=self.site,
                pip=self._fake_pip(omit="pkga==1.0.0"),
            )
        self.assertIn("No matching distribution", str(cm.exception))


class OfflineRuntimeInstall(unittest.TestCase):
    def setUp(self) -> None:
        self._tmp = tempfile.TemporaryDirectory()
        self.addCleanup(self._tmp.cleanup)
        self.root = Path(self._tmp.name)

    def test_install_stages_verifies_and_activates(self) -> None:
        wh = self.root / "wh"
        make_wheel(wh, "pkgc", "1.0.0", modules=("pkgc",))
        target = self.root / "prefix" / "venv"
        result = transfer.install_runtime(
            target, wh, requirements={"pkgc": "1.0.0"}, probe_imports=["pkgc"],
        )
        self.assertTrue((target / "bin" / "python").exists())
        proc = subprocess.run(
            [str(target / "bin" / "python"), "-c", "import pkgc; print(pkgc.VALUE)"],
            capture_output=True, text=True, timeout=60,
        )
        self.assertEqual(proc.stdout.strip(), "pkgc")
        self.assertEqual(result["requirements"], {"pkgc": "1.0.0"})
        leftovers = [p.name for p in self.root.glob("prefix/.*")]
        self.assertEqual(leftovers, [])

    def test_install_omits_unlisted_transitive_wheels(self) -> None:
        wh = self.root / "closure-wh"
        make_wheel(wh, "pkgd", "1.0.0", requires=("pkgc==1.0.0",), modules=("pkgd",))
        make_wheel(wh, "pkgc", "1.0.0", modules=("pkgc",))
        target = self.root / "prefix2" / "venv"
        transfer.install_runtime(target, wh, requirements={"pkgd": "1.0.0"})
        site = next((target / "lib").glob("python3.*/site-packages"))
        self.assertTrue((site / "pkgd.py").exists())
        self.assertFalse((site / "pkgc.py").exists(),
                         "--no-deps must keep unlisted wheels out of the runtime")

    def test_failure_preserves_active_install(self) -> None:
        wh = self.root / "wh"
        make_wheel(wh, "pkgc", "1.0.0", modules=("pkgc",))
        target = self.root / "prefix" / "venv"
        transfer.install_runtime(target, wh, requirements={"pkgc": "1.0.0"})
        broken = self.root / "broken"
        broken.mkdir()
        make_wheel(broken, "pkgc", "1.0.0", modules=("pkgc",))
        good = make_wheel(broken, "pkgd", "1.0.0", modules=("pkgd",))
        data = good.read_bytes()
        good.write_bytes(data[: len(data) // 2])
        with self.assertRaisesRegex(transfer.TransferError, "pkgd"):
            transfer.install_runtime(target, broken,
                                     requirements={"pkgd": "1.0.0", "pkgc": "1.0.0"})
        proc = subprocess.run(
            [str(target / "bin" / "python"), "-c", "import pkgc; print('ok')"],
            capture_output=True, text=True, timeout=60,
        )
        self.assertEqual(proc.stdout.strip(), "ok")
        self.assertEqual([p.name for p in self.root.glob("prefix/.*")], [])

    def test_console_script_launcher_runs_after_activation(self) -> None:
        # pip writes the launcher with the hidden staging path in its shebang;
        # commit_runtime must relocate it or the activated venv is unusable.
        wh = self.root / "wh"
        make_wheel(wh, "pkgc", "1.0.0",
                   modules=(("pkgc", "VALUE = 'pkgc'\n\ndef main():\n    print('ran')\n"),),
                   entry_points={"fake-chat": "pkgc:main"})
        target = self.root / "prefix" / "venv"
        transfer.install_runtime(target, wh, requirements={"pkgc": "1.0.0"},
                                 probe_imports=["pkgc"])
        launcher = target / "bin" / "fake-chat"
        self.assertTrue(launcher.is_file())
        self.assertNotIn(str(self.root / "prefix" / ".venv.staging"),
                         launcher.read_text(),
                         "launcher still points into the discarded staging dir")
        unrelated = self.root / "unrelated"
        unrelated.mkdir()
        proc = subprocess.run([str(launcher), "--help"], cwd=unrelated,
                              capture_output=True, text=True, timeout=60)
        self.assertEqual(proc.returncode, 0, proc.stderr)
        self.assertIn("ran", proc.stdout)


class GenerationActivation(unittest.TestCase):
    """Candidates stage beside venv_target; activation is an atomic symlink swap."""

    def setUp(self) -> None:
        self._tmp = tempfile.TemporaryDirectory()
        self.addCleanup(self._tmp.cleanup)
        self.root = Path(self._tmp.name)
        self.prefix = self.root / "prefix"
        self.target = self.prefix / "venv"

    @staticmethod
    def _wh(root: Path, version: str, value: str) -> Path:
        wh = root / f"wh{version}"
        make_wheel(wh, "pkgc", version,
                   modules=(("pkgc", f"VALUE = '{value}'\n\n"
                               "def main():\n    print(VALUE)\n"),),
                   entry_points={"fake-chat": "pkgc:main"})
        return wh

    def _install(self, wh: Path, version: str) -> None:
        transfer.install_runtime(self.target, wh, requirements={"pkgc": version},
                                 probe_imports=["pkgc"])

    def _run(self, args=None):
        return subprocess.run([str(self.target / "bin" / "fake-chat"), *(args or [])],
                              cwd=self.root, capture_output=True, text=True, timeout=60)

    def _gens(self) -> list[str]:
        return sorted(p.name for p in self.prefix.glob("venv.gen-*"))

    def test_active_install_survives_candidate_staging(self) -> None:
        self._install(self._wh(self.root, "1.0.0", "one"), "1.0.0")
        gen1 = Path(os.path.realpath(self.target))
        self.assertTrue(self.target.is_symlink(), "activated venv must be a symlink")
        staged_seen, proceed = threading.Event(), threading.Event()
        observed: dict = {}
        real_verify = transfer.verify_venv_records

        def spy(venv_path, requirements):
            proc = self._run()
            observed["during"] = (proc.returncode, proc.stdout.strip(),
                                  self.target.is_symlink(),
                                  Path(os.path.realpath(self.target)) == gen1)
            staged_seen.set()
            proceed.wait(30)
            return real_verify(venv_path, requirements)

        outcome: dict = {}

        def work():
            try:
                self._install(self._wh(self.root, "2.0.0", "two"), "2.0.0")
            except BaseException as exc:  # surfaced on the main thread
                outcome["err"] = exc

        with mock.patch.object(transfer, "verify_venv_records", spy):
            worker = threading.Thread(target=work)
            worker.start()
            self.assertTrue(staged_seen.wait(60), "candidate never reached verification")
            # the old install is still exactly what callers see mid-staging
            self.assertEqual(observed["during"], (0, "one", True, True))
            proceed.set()
            worker.join(120)
        self.assertNotIn("err", outcome, getattr(outcome.get("err"), "stderr", None))
        proc = self._run()
        self.assertEqual((proc.returncode, proc.stdout.strip()), (0, "two"))
        self.assertNotEqual(Path(os.path.realpath(self.target)), gen1)
        self.assertFalse(gen1.exists(), "replaced generation must be pruned")
        self.assertEqual(len(self._gens()), 1)

    def test_failed_candidate_leaves_no_partial_target(self) -> None:
        self._install(self._wh(self.root, "1.0.0", "one"), "1.0.0")
        gen1 = Path(os.path.realpath(self.target))
        broken = self._wh(self.root, "2.0.0", "two")
        wheel = next(broken.glob("pkgc-2.0.0-*.whl"))
        data = wheel.read_bytes()
        wheel.write_bytes(data[: len(data) // 2])
        with self.assertRaises(transfer.TransferError):
            self._install(broken, "2.0.0")
        self.assertTrue(self.target.is_symlink())
        self.assertEqual(Path(os.path.realpath(self.target)), gen1)
        proc = self._run()
        self.assertEqual((proc.returncode, proc.stdout.strip()), (0, "one"))
        self.assertEqual(self._gens(), [gen1.name],
                         "failed candidate generation must be removed")
        self.assertEqual([p.name for p in self.prefix.glob(".venv.*")], [])

    def test_legacy_real_dir_migrates_and_rolls_back(self) -> None:
        # a real directory from another installer: migrated to backup at commit
        subprocess.run([sys.executable, "-m", "venv", "--clear", str(self.target)],
                       check=True, capture_output=True, timeout=60)
        self.assertFalse(self.target.is_symlink())
        self._install(self._wh(self.root, "1.0.0", "one"), "1.0.0")
        self.assertTrue(self.target.is_symlink())
        self.assertEqual([p.name for p in self.prefix.glob(".venv.*")],
                         [], "migrated backup must be pruned after success")
        proc = self._run()
        self.assertEqual((proc.returncode, proc.stdout.strip()), (0, "one"))
        # staging failure over a legacy real dir must not touch the target
        self.target.unlink()
        subprocess.run([sys.executable, "-m", "venv", "--clear", str(self.target)],
                       check=True, capture_output=True, timeout=60)
        broken = self._wh(self.root, "9.0.0", "nine")
        wheel = next(broken.glob("pkgc-9.0.0-*.whl"))
        data = wheel.read_bytes()
        wheel.write_bytes(data[: len(data) // 2])
        with self.assertRaises(transfer.TransferError):
            self._install(broken, "9.0.0")
        self.assertFalse(self.target.is_symlink())
        self.assertTrue((self.target / "bin" / "python").exists(),
                        "legacy target must survive a failed staging")

    def test_foreign_symlink_target_refused(self) -> None:
        decoy = self.root / "decoy"
        decoy.mkdir()
        (decoy / "keep").write_bytes(b"keep")
        self.target.parent.mkdir(parents=True)
        self.target.symlink_to(decoy)
        with self.assertRaisesRegex(transfer.TransferError, "outside transfer ownership"):
            self._install(self._wh(self.root, "1.0.0", "one"), "1.0.0")
        self.assertTrue(self.target.is_symlink())
        self.assertEqual(Path(os.readlink(self.target)), decoy)
        self.assertTrue((decoy / "keep").exists(), "foreign target must be untouched")
        self.assertEqual(self._gens(), [], "failed candidate must not linger")

    def test_double_upgrade_prunes_retired_generation(self) -> None:
        self._install(self._wh(self.root, "1.0.0", "one"), "1.0.0")
        self._install(self._wh(self.root, "2.0.0", "two"), "2.0.0")
        self._install(self._wh(self.root, "3.0.0", "three"), "3.0.0")
        proc = self._run()
        self.assertEqual((proc.returncode, proc.stdout.strip()), (0, "three"))
        self.assertEqual(len(self._gens()), 1)


class AppWheelBytes(unittest.TestCase):
    """The portable app bytes: parsed install.sh lists, wheel shape, RECORD."""

    def setUp(self) -> None:
        self._tmp = tempfile.TemporaryDirectory()
        self.addCleanup(self._tmp.cleanup)
        self.root = Path(self._tmp.name)

    def test_app_wheel_carries_packages_assistant_static_and_demo(self) -> None:
        out = self.root / "wh"
        entry = transfer.build_app_wheel(out, repo=REPO)
        self.assertEqual(entry["version"], transfer.APP_VERSION)
        self.assertEqual(entry["wheel"],
                         f"mlx_omarchy_assistant-{transfer.APP_VERSION}"
                         "-py3-none-any.whl")
        self.assertEqual(entry["size"], (out / entry["wheel"]).stat().st_size)
        with zipfile.ZipFile(out / entry["wheel"]) as zf:
            names = set(zf.namelist())
            for member in ("mlx_omarchy_serve/catalog.json",
                           "mlx_omarchy_laya/sequence.py",
                           "mlx_omarchy_bonsai2/packed.py",
                           "mlx_omarchy_assistant/__main__.py",
                           "mlx_omarchy_assistant/static/index.html",
                           "coreml/reference.py", "coreml/parakeet_dictation.py",
                           "chat.py"):
                self.assertIn(member, names)
            self.assertFalse([n for n in names if "__pycache__" in n or n.endswith(".pyc")])
            entry_points = zf.read(
                f"mlx_omarchy_assistant-{transfer.APP_VERSION}.dist-info/"
                "entry_points.txt").decode()
            for launcher in transfer.APP_LAUNCHERS:
                self.assertRegex(entry_points, rf"\n{launcher} = .+\n", launcher)
            # every RECORD line matches the member bytes it claims
            record = zf.read(f"mlx_omarchy_assistant-{transfer.APP_VERSION}"
                             ".dist-info/RECORD").decode()
            listed = set()
            for line in record.splitlines():
                path, digest, size = line.split(",")
                if not digest:
                    self.assertEqual(path, f"mlx_omarchy_assistant-{transfer.APP_VERSION}"
                                           ".dist-info/RECORD")
                    continue
                listed.add(path)
                data = zf.read(path)
                b64 = base64.urlsafe_b64encode(
                    hashlib.sha256(data).digest()).rstrip(b"=").decode()
                self.assertEqual(digest, "sha256=" + b64, path)
                self.assertEqual(int(size), len(data), path)
            self.assertEqual(listed, names - {
                f"mlx_omarchy_assistant-{transfer.APP_VERSION}.dist-info/RECORD"})

    def test_build_names_missing_repo_pieces(self) -> None:
        empty = self.root / "empty-repo"
        empty.mkdir()
        with self.assertRaisesRegex(transfer.TransferError, "install.sh"):
            transfer.build_app_wheel(self.root / "wh", repo=empty)
        repo = self.root / "repo"
        repo.mkdir()
        (repo / "install.sh").write_text(
            'FAKE_PKG="$PREFIX/mlx_omarchy_fake"\nmkdir -p "$FAKE_PKG"\n'
            "for fake_file in gone.py; do\n  :\ndone\n")
        with self.assertRaisesRegex(transfer.TransferError, "gone.py"):
            transfer.build_app_wheel(self.root / "wh", repo=repo)
        # a checkout without the demo entry point is refused by name too
        shutil.copytree(REPO / "serve", repo / "serve",
                        ignore=shutil.ignore_patterns("__pycache__"))
        (repo / "overlay" / "tools").mkdir(parents=True)
        shutil.copytree(REPO / "overlay" / "tools" / "coreml",
                        repo / "overlay" / "tools" / "coreml",
                        ignore=shutil.ignore_patterns("__pycache__"))
        (repo / "install.sh").write_text("#!/usr/bin/env bash\nsay() { :; }\n")
        with self.assertRaisesRegex(transfer.TransferError, "demo/chat.py"):
            transfer.build_app_wheel(self.root / "wh", repo=repo)


class AppInstallTransfer(Base):
    """Disconnected-target proof: real app wheel through a real offline venv."""

    def _export_app_bundle(self, name: str) -> Path:
        entry = transfer.build_app_wheel(self.wh, repo=REPO)
        self.export(required=[entry["wheel"]],
                    probe_imports=["mlx_omarchy_assistant"], out=name)
        return self.bundle_path(name)

    def _run_launcher(self, venv: Path, script: str, cwd: Path):
        return subprocess.run([str(venv / "bin" / script), "--help"], cwd=cwd,
                              capture_output=True, text=True, timeout=120)

    def test_transfer_installs_runnable_chat_launcher_without_repo(self) -> None:
        bundle = self._export_app_bundle("app.zip")
        info = transfer.inspect_bundle(bundle)
        self.assertIn("mlx-omarchy-assistant", info["requirements"])
        venv = self.dst_home / "venv"
        transfer.install_bundle(self.dst_home, bundle, {"apache-2.0"},
                                venv_target=venv, platform_info=dict(PLAT))
        unrelated = self.root / "unrelated-cwd"
        unrelated.mkdir()
        for script, needle in (("mlx-omarchy-chat", "usage: mlx-omarchy-assistant"),
                               ("mlx-omarchy-serve", "usage:"),
                               ("mlx-omarchy-demo", "usage: mlx-omarchy-demo")):
            proc = self._run_launcher(venv, script, unrelated)
            self.assertEqual(proc.returncode, 0, f"{script}: {proc.stderr}")
            self.assertIn(needle, proc.stdout)
        site = next((venv / "lib").glob("python3.*/site-packages"))
        self.assertTrue((site / "mlx_omarchy_assistant" / "static" / "index.html")
                        .is_file())
        self.assertTrue((site / "mlx_omarchy_serve" / "catalog.json").is_file())
        # installed app bytes equal the wheel payload (RECORD hashes)
        transfer.verify_venv_records(venv, {"mlx-omarchy-assistant": "1.0.0"})
        self.assertTrue(venv.is_symlink(), "activated venv must be a symlink")
        self.assertEqual([p.name for p in self.dst_home.glob(".venv*")], [])
        self.assertLessEqual(len(list(self.dst_home.glob("venv.gen-*"))), 1)

    def test_installed_app_rebuilds_its_wheel_without_repo(self) -> None:
        bundle = self._export_app_bundle("src.zip")
        venv = self.dst_home / "venv"
        transfer.install_bundle(self.dst_home, bundle, {"apache-2.0"},
                                venv_target=venv, platform_info=dict(PLAT))
        # inside the installed venv there is no checkout (DEFAULT_REPO holds no
        # install.sh), so build_app_wheel must fall back to the installed RECORD
        code = ("import json, sys\n"
                "from mlx_omarchy_assistant import transfer\n"
                "print(json.dumps(transfer.build_app_wheel(sys.argv[1])))\n")
        out = self.root / "reexport"
        proc = subprocess.run(
            [str(venv / "bin" / "python"), "-c", code, str(out)],
            capture_output=True, text=True, timeout=120)
        self.assertEqual(proc.returncode, 0, proc.stderr)
        entry = json.loads(proc.stdout)
        self.assertEqual(entry["version"], "1.0.0")
        with zipfile.ZipFile(out / entry["wheel"]) as zf:
            names = set(zf.namelist())
        self.assertIn("mlx_omarchy_assistant/static/index.html", names)
        self.assertIn("chat.py", names)
        self.assertIn("mlx_omarchy_serve/catalog.json", names)

    def test_failed_reinstall_preserves_runnable_launcher(self) -> None:
        bundle = self._export_app_bundle("a1.zip")
        venv = self.dst_home / "venv"
        transfer.install_bundle(self.dst_home, bundle, {"apache-2.0"},
                                venv_target=venv, platform_info=dict(PLAT))
        real_replace = transfer.os.replace

        def boom(src, dst, *a, **kw):
            if "pair-locks" in str(dst):
                raise OSError("disk gone")
            return real_replace(src, dst, *a, **kw)

        with mock.patch.object(transfer.os, "replace", side_effect=boom):
            with self.assertRaisesRegex(transfer.TransferError, "disk gone"):
                transfer.install_bundle(self.dst_home, bundle, {"apache-2.0"},
                                        venv_target=venv, platform_info=dict(PLAT))
        unrelated = self.root / "unrelated2"
        unrelated.mkdir()
        proc = self._run_launcher(venv, "mlx-omarchy-chat", unrelated)
        self.assertEqual(proc.returncode, 0, proc.stderr)
        self.assertIn("usage: mlx-omarchy-assistant", proc.stdout)
        self.assertEqual([p.name for p in self.dst_home.glob(".venv*")], [])
        self.assertEqual(len(list(self.dst_home.glob("venv.gen-*"))), 1,
                         "rolled-back candidate generation must be gone")


class AppTransferRequests(Base):
    """plan/prepare request surfaces carry the app bytes like any other wheel."""

    def test_plan_and_prepare_report_and_carry_app_bytes(self) -> None:
        (self.src_home / "assistant" / "pair-locks").mkdir(parents=True)
        (self.src_home / "assistant" / "pair-locks" / "everyday.json").write_text(
            json.dumps(self.lock))
        fixtures, site = make_site_with_wheels(
            self.root, [("pkgc", "1.0.0", (), ("pkgc",))])
        plan = transfer.run_transfer_request(self.src_home, {
            "action": "plan", "pair_ids": ["everyday"],
            "site_path": str(site), "roots": ["pkgc"]})
        self.assertIn("mlx-omarchy-assistant", plan["requirements"])
        self.assertIn("mlx-omarchy-chat", plan["app"]["launchers"])
        self.assertGreater(plan["app"]["bytes"], 0)
        out = self.root / "req.zip"
        pip = make_fake_pip(self.root / "fakepip.py", fixtures)
        prepared = transfer.run_transfer_request(self.src_home, {
            "action": "prepare", "pair_ids": ["everyday"], "output": str(out),
            "approved_licenses": ["apache-2.0"],
            "site_path": str(site), "roots": ["pkgc"], "wheel_caches": [],
            "probe_imports": ["pkgc"], "pip": pip, "platform": dict(PLAT)})
        self.assertIn("mlx-omarchy-assistant", prepared["requirements"])
        self.assertIn("mlx-omarchy-chat", prepared["app"]["launchers"])
        with zipfile.ZipFile(out) as zf:
            app_wheels = [n for n in zf.namelist()
                          if n.startswith("wheels/mlx_omarchy_assistant-")]
            self.assertEqual(len(app_wheels), 1)
        manifest = json.loads(zipfile.ZipFile(out).read(transfer.MANIFEST_NAME))
        self.assertIn("mlx_omarchy_assistant", manifest["probe_imports"])
        # install side probes the app even when the caller forgot to ask for it
        venv = self.dst_home / "venv"
        transfer.install_bundle(self.dst_home, out, {"apache-2.0"},
                                venv_target=venv, platform_info=dict(PLAT))
        site = next((venv / "lib").glob("python3.*/site-packages"))
        self.assertTrue((site / "mlx_omarchy_assistant" / "__init__.py").is_file())


class VoiceAssets(Base):
    def test_voice_roundtrip_verbatim_with_approval(self) -> None:
        pack = self._voice_dir()
        manifest = self.export(voice=[pack])
        self.assertEqual(manifest["voice"][0]["pack_id"], "qwen3-tts-0.6b-customvoice-4bit")
        self.assertEqual(manifest["voice"][0]["bytes"],
                         4096 + 2 + 1024 + (pack / "manifest.json").stat().st_size)
        result = self.import_()
        dest = self.dst_home / "voice" / "qwen3-tts-0.6b-customvoice-4bit"
        self.assertEqual((dest / "model.safetensors").read_bytes(), b"V" * 4096)
        self.assertEqual((dest / "speech_tokenizer" / "model.safetensors").read_bytes(),
                         b"T" * 1024)
        self.assertEqual(json.loads((dest / "manifest.json").read_text())["license"],
                         "apache-2.0")

    def test_voice_requires_license_approval(self) -> None:
        pack = self._voice_dir()
        with self.assertRaises(transfer.LicenseNotApproved):
            self.export(voice=[pack], approved=set())
        self.assertFalse(self.bundle_path().exists())

    def test_voice_manifest_mismatch_named(self) -> None:
        pack = self._voice_dir(corrupt=True)
        with self.assertRaisesRegex(transfer.TransferError, "model.safetensors"):
            self.export(voice=[pack])

    def test_voice_import_refuses_without_approval(self) -> None:
        self.export(voice=[self._voice_dir()])
        with self.assertRaises(transfer.LicenseNotApproved):
            self.import_(approved=set())
        self.assertFalse((self.dst_home / "voice").exists())


class NoNetwork(Base):
    def test_import_performs_no_network_calls(self) -> None:
        self.export()
        with mock.patch.object(socket, "socket", side_effect=AssertionError("network")), \
                mock.patch.object(socket, "create_connection",
                                  side_effect=AssertionError("network")), \
                mock.patch.object(socket, "socketpair",
                                  side_effect=AssertionError("network")):
            self.import_()

    def test_offline_install_performs_no_network_calls(self) -> None:
        wh = self.root / "wh"
        make_wheel(wh, "pkgc", "1.0.0", modules=("pkgc",))
        with mock.patch.object(socket, "socket", side_effect=AssertionError("network")), \
                mock.patch.object(socket, "create_connection",
                                  side_effect=AssertionError("network")):
            transfer.install_runtime(self.root / "prefix" / "venv", wh,
                                     requirements={"pkgc": "1.0.0"},
                                     probe_imports=["pkgc"])
        self.assertTrue((self.root / "prefix" / "venv" / "bin" / "python").exists())


class RuntimeRecords(unittest.TestCase):
    def setUp(self) -> None:
        self._tmp = tempfile.TemporaryDirectory()
        self.addCleanup(self._tmp.cleanup)
        self.root = Path(self._tmp.name)
        self.wh = self.root / "wh"
        make_wheel(self.wh, "pkgc", "1.0.0", modules=("pkgc",))
        self.target = self.root / "prefix" / "venv"
        transfer.install_runtime(self.target, self.wh, requirements={"pkgc": "1.0.0"})

    def site(self) -> Path:
        return next((self.target / "lib").glob("python3.*/site-packages"))

    def test_record_verification_detects_tampered_file(self) -> None:
        (self.site() / "pkgc.py").write_text("VALUE = 'evil'\n")
        with self.assertRaisesRegex(transfer.TransferError, "pkgc"):
            transfer.verify_venv_records(self.target, {"pkgc": "1.0.0"})

    def test_record_verification_rejects_version_drift(self) -> None:
        with self.assertRaisesRegex(transfer.TransferError, "provenance"):
            transfer.verify_venv_records(self.target, {"pkgc": "2.0.0"})

    def test_record_verification_passes_clean_install(self) -> None:
        transfer.verify_venv_records(self.target, {"pkgc": "1.0.0"})


class InstallBundleTransaction(Base):
    def test_combined_install_activates_assets_and_venv(self) -> None:
        make_wheel(self.wh, "pkgc", "1.0.0", modules=("pkgc",))
        self.export(required=["pkgc-1.0.0-py3-none-any.whl"], probe_imports=["pkgc"],
                    out="rt.zip")
        venv = self.dst_home / "venv"
        result = transfer.install_bundle(self.dst_home, self.bundle_path("rt.zip"),
                                         {"apache-2.0"}, venv_target=venv,
                                         platform_info=dict(PLAT))
        proc = subprocess.run(
            [str(venv / "bin" / "python"), "-c", "import pkgc; print(pkgc.VALUE)"],
            capture_output=True, text=True, timeout=60)
        self.assertEqual(proc.stdout.strip(), "pkgc")
        self.assertTrue((self.dst_home / "assistant" / "imports" / "everyday" /
                         "transfer-lock.json").exists())
        self.assertEqual(result["runtime"]["requirements"], {"pkgc": "1.0.0"})
        self.assertEqual([p.name for p in self.dst_home.glob(".venv*")], [])

    def test_combined_failure_preserves_entire_active_install(self) -> None:
        make_wheel(self.wh, "pkgc", "1.0.0", modules=("pkgc",))
        self.export(required=["pkgc-1.0.0-py3-none-any.whl"], probe_imports=["pkgc"],
                    out="good.zip")
        venv = self.dst_home / "venv"
        transfer.install_bundle(self.dst_home, self.bundle_path("good.zip"),
                                {"apache-2.0"}, venv_target=venv,
                                platform_info=dict(PLAT))
        # second bundle: same pair with new content but a corrupt runtime wheel
        (self.chat_dir / "config.json").write_bytes(b'{"v":9}')
        make_wheel(self.wh, "pkgd", "1.0.0", modules=("pkgd",))
        broken = self.wh / "pkgd-1.0.0-py3-none-any.whl"
        data = broken.read_bytes()
        broken.write_bytes(data[: len(data) // 2])
        self.export(required=["pkgd-1.0.0-py3-none-any.whl"], out="bad.zip")
        with self.assertRaises(transfer.TransferError):
            transfer.install_bundle(self.dst_home, self.bundle_path("bad.zip"),
                                    {"apache-2.0"}, venv_target=venv,
                                    platform_info=dict(PLAT))
        # assets unchanged, venv unchanged, no staging leftovers
        self.assertEqual(
            (self.dst_home / "assistant" / "imports" / "everyday" / "chat" / "config.json"
             ).read_bytes(), b"{}")
        proc = subprocess.run(
            [str(venv / "bin" / "python"), "-c", "import pkgc, sys; print('ok')"],
            capture_output=True, text=True, timeout=60)
        self.assertEqual(proc.stdout.strip(), "ok")
        self.assertEqual([p.name for p in self.dst_home.glob(".venv*")], [])
        self.assertFalse((self.dst_home / "transfer" / "staging").exists())

    def test_install_bundle_without_venv_matches_import_bundle(self) -> None:
        self.export(out="plain.zip")
        result = transfer.install_bundle(self.dst_home, self.bundle_path("plain.zip"),
                                         {"apache-2.0"}, venv_target=None,
                                         platform_info=dict(PLAT))
        self.assertIsNone(result["runtime"])
        self.assertTrue((self.dst_home / "assistant" / "imports" / "everyday" /
                         "transfer-lock.json").exists())

    def test_install_request_defaults_venv(self) -> None:
        make_wheel(self.wh, "pkgc", "1.0.0", modules=("pkgc",))
        self.export(required=["pkgc-1.0.0-py3-none-any.whl"], probe_imports=["pkgc"],
                    out="rt.zip")
        result = transfer.run_transfer_request(self.dst_home, {
            "action": "install", "bundle": str(self.bundle_path("rt.zip")),
            "approved_licenses": ["apache-2.0"], "platform": dict(PLAT)})
        venv = self.dst_home / "venv"
        self.assertIsNotNone(result["runtime"])
        self.assertEqual(result["runtime"]["venv"], str(venv))
        proc = subprocess.run(
            [str(venv / "bin" / "python"), "-c", "import pkgc; print('ok')"],
            capture_output=True, text=True, timeout=60)
        self.assertEqual(proc.stdout.strip(), "ok")

    def test_voice_import_preserves_unrelated_packs(self) -> None:
        # a pre-existing pack on the destination that this bundle does not carry
        other = self.dst_home / "voice" / "pack-a"
        other.mkdir(parents=True)
        (other / "keep.txt").write_bytes(b"keep me")
        self.export(voice=[self._voice_dir()])
        self.import_()
        self.assertTrue((other / "keep.txt").exists(),
                        "unrelated voice pack must survive import")
        self.assertTrue((self.dst_home / "voice" / "qwen3-tts-0.6b-customvoice-4bit" /
                         "model.safetensors").exists())

    def test_import_rejects_undeclared_voice_pack_and_reserved_pair(self) -> None:
        self.export()
        self._rebuild("evilvoice.zip",
                      member_fn=lambda members: {**members,
                                                 "voice/evil/model.bin": b"hostile"})
        with self.assertRaisesRegex(transfer.UnsafeArchive, "evil"):
            self.import_(bundle="evilvoice.zip")
        # reserved pair id on import side
        def add_reserved(m):
            m["pairs"].append({"pair_id": "wheels", "arch": ["t6021"],
                               "licenses": [], "file_count": 0, "bytes": 0})
            return m
        self._rebuild("res.zip", manifest_fn=add_reserved)
        with self.assertRaisesRegex(transfer.UnsafeArchive, "reserved"):
            self.import_(bundle="res.zip")

    def _members(self) -> dict:
        with zipfile.ZipFile(self.bundle_path()) as zf:
            return {n: zf.read(n) for n in zf.namelist()}

    def test_hostile_manifest_license_omission_and_decoy_rejected(self) -> None:
        self.export()
        # omission: manifest claims no licenses while lock bytes carry apache-2.0
        def omit(m):
            m["licenses"] = {}
            m["pairs"][0]["licenses"] = []
            return m
        self._rebuild("omit.zip", manifest_fn=omit)
        with self.assertRaises(transfer.TransferError):
            self.import_(bundle="omit.zip")
        # decoy: manifest lists 'mit' but the embedded lock says apache-2.0
        def decoy(m):
            m["licenses"] = {"mit": {"models": ["qwen3.8-2b-4bit"], "bytes": 1}}
            m["pairs"][0]["licenses"] = ["mit"]
            return m
        self._rebuild("decoy.zip", manifest_fn=decoy)
        with self.assertRaisesRegex(transfer.TransferError, "do not match"):
            self.import_(bundle="decoy.zip", approved={"mit"})

    def test_import_revalidates_embedded_lock_schema(self) -> None:
        self.export()
        def break_lock(members):
            lock = json.loads(members["everyday/lock.json"])
            del lock["licenses"]
            members["everyday/lock.json"] = json.dumps(lock).encode()
            return members
        self._rebuild("badlock.zip", member_fn=break_lock)
        with self.assertRaisesRegex(transfer.TransferError, "licenses"):
            self.import_(bundle="badlock.zip")

    def test_complete_bundle_requires_consistent_runtime_manifest(self) -> None:
        self.export()
        def empty_runtime(m):
            m["requirements"] = {}
            m["wheels"] = []
            return m
        self._rebuild("emptyrt.zip", manifest_fn=empty_runtime)
        with self.assertRaisesRegex(transfer.TransferError, "wheels_complete"):
            self.import_(bundle="emptyrt.zip")
        def wrong_wheel_hash(m):
            m["wheels"][0]["sha256"] = "0" * 64
            return m
        self._rebuild("whash.zip", manifest_fn=wrong_wheel_hash)
        with self.assertRaisesRegex(transfer.TransferError, "mlx_core"):
            self.import_(bundle="whash.zip")
        def extra_requirement(m):
            m["requirements"]["ghost"] = "1.0.0"
            return m
        self._rebuild("ghostreq.zip", manifest_fn=extra_requirement)
        with self.assertRaisesRegex(transfer.TransferError, "requirements"):
            self.import_(bundle="ghostreq.zip")

    def _rebuild(self, out: str, *, manifest_fn=None, member_fn=None) -> None:
        members = self._members()
        manifest = json.loads(members[transfer.MANIFEST_NAME])
        if member_fn:
            members = member_fn(members)
            for name, data in members.items():
                if name == transfer.MANIFEST_NAME:
                    continue
                manifest["files"][name] = {"sha256": hashlib.sha256(data).hexdigest(),
                                           "size": len(data)}
            manifest["total_bytes"] = sum(e["size"] for e in manifest["files"].values())
        if manifest_fn:
            manifest = manifest_fn(manifest)
        members[transfer.MANIFEST_NAME] = json.dumps(manifest).encode()
        self.raw_zip(self.bundle_path(out), sorted(members.items()))

    def test_install_activates_pair_locks_readable_by_fresh_pairmanager(self) -> None:
        self.export(out="l.zip")
        result = transfer.install_bundle(self.dst_home, self.bundle_path("l.zip"),
                                         {"apache-2.0"}, venv_target=None,
                                         platform_info=dict(PLAT))
        self.assertTrue(result["restart_required"])
        lock = transfer.load_lock(self.dst_home, "everyday")
        self.assertIsNotNone(lock)
        self.assertEqual(lock["pair_id"], "everyday")
        chat_dir = Path(lock["models"]["chat"]["path"])
        self.assertTrue(chat_dir.is_dir(), "imported lock must point at real artifacts")
        self.assertEqual((chat_dir / "model.safetensors").read_bytes(), b"Q" * 4096)
        self.assertEqual(lock["models"]["chat"]["revision"], "a" * 40)
        self.assertTrue(result["locks"][0]["lock_path"].endswith("everyday.json"))

    def test_failed_install_preserves_previous_active_lock(self) -> None:
        self.export(out="l1.zip")
        transfer.install_bundle(self.dst_home, self.bundle_path("l1.zip"),
                                {"apache-2.0"}, venv_target=None,
                                platform_info=dict(PLAT))
        old = transfer.load_lock(self.dst_home, "everyday")
        # new bundle with changed lock content, but corrupt payload → verification fails
        self.lock["context_tokens"] = 4096
        (self.chat_dir / "config.json").write_bytes(b'{"v":9}')
        self.export(out="l2.zip")
        self.rewrite_zip(self.bundle_path("l2.zip"), self.bundle_path("l2bad.zip"),
                         lambda n, d: d[:-1] + bytes([d[-1] ^ 0xFF])
                         if n.endswith("config.json") else d)
        with self.assertRaises(transfer.VerificationFailed):
            transfer.import_bundle(self.dst_home, self.bundle_path("l2bad.zip"),
                                   {"apache-2.0"}, platform_info=dict(PLAT))
        current = transfer.load_lock(self.dst_home, "everyday")
        self.assertEqual(current["context_tokens"], old["context_tokens"])

    def test_lock_write_failure_rolls_back_venv_assets_and_locks(self) -> None:
        make_wheel(self.wh, "pkgc", "1.0.0", modules=("pkgc",))
        self.export(required=["pkgc-1.0.0-py3-none-any.whl"], probe_imports=["pkgc"],
                    out="g1.zip")
        venv = self.dst_home / "venv"
        transfer.install_bundle(self.dst_home, self.bundle_path("g1.zip"),
                                {"apache-2.0"}, venv_target=venv,
                                platform_info=dict(PLAT))
        old_lock = transfer.load_lock(self.dst_home, "everyday")
        real_replace = transfer.os.replace

        def boom(src, dst, *a, **kw):
            if "pair-locks" in str(dst):
                raise OSError("disk gone")
            return real_replace(src, dst, *a, **kw)

        self.export(required=["pkgc-1.0.0-py3-none-any.whl"], out="g2.zip")
        with mock.patch.object(transfer.os, "replace", side_effect=boom):
            with self.assertRaisesRegex(transfer.TransferError, "disk gone"):
                transfer.install_bundle(self.dst_home, self.bundle_path("g2.zip"),
                                        {"apache-2.0"}, venv_target=venv,
                                        platform_info=dict(PLAT))
        # venv restored, assets restored, previous lock intact
        proc = subprocess.run(
            [str(venv / "bin" / "python"), "-c", "import pkgc; print('ok')"],
            capture_output=True, text=True, timeout=60)
        self.assertEqual(proc.stdout.strip(), "ok")
        self.assertEqual(transfer.load_lock(self.dst_home, "everyday")["context_tokens"],
                         old_lock["context_tokens"])
        self.assertEqual(
            (self.dst_home / "assistant" / "imports" / "everyday" / "chat" / "config.json"
             ).read_bytes(), b"{}")
        self.assertEqual([p.name for p in self.dst_home.glob(".venv*")], [])


class TransferRequests(Base):
    def test_inspect_op_and_path_validation(self) -> None:
        self.export()
        info = transfer.run_transfer_request(
            self.dst_home, {"action": "inspect", "bundle": str(self.bundle_path())})
        self.assertIn("bundle_id", info)
        with self.assertRaisesRegex(transfer.TransferError, "no bundle"):
            transfer.run_transfer_request(
                self.dst_home, {"action": "inspect",
                                "bundle": str(self.root / "missing.zip")})
        with self.assertRaisesRegex(transfer.TransferError, "unknown"):
            transfer.run_transfer_request(self.dst_home, {"action": "teleport"})

    def test_prepare_and_install_ops_end_to_end(self) -> None:
        (self.src_home / "assistant" / "pair-locks").mkdir(parents=True)
        (self.src_home / "assistant" / "pair-locks" / "everyday.json").write_text(
            json.dumps(self.lock))
        self._voice_dir()
        fixtures, site = make_site_with_wheels(
            self.root, [("pkgc", "1.0.0", (), ("pkgc",))])
        pip = make_fake_pip(self.root / "fakepip.py", fixtures)
        plan = transfer.run_transfer_request(self.src_home, {
            "action": "plan", "pair_ids": ["everyday"], "voice": True,
            "site_path": str(site), "roots": ["pkgc"], "wheel_caches": [],
        })
        # plan NEVER downloads: uncached wheels are reported as data, not captured
        self.assertFalse(plan["wheels_complete"])
        self.assertEqual(plan["missing_wheels"], ["pkgc==1.0.0"])
        self.assertEqual(plan["pairs"][0]["bytes"], 4096 + 2 + 2 + 2048)
        self.assertIn("apache-2.0", plan["licenses"])
        out = self.root / "req.zip"
        prepared = transfer.run_transfer_request(self.src_home, {
            "action": "prepare", "pair_ids": ["everyday"], "output": str(out),
            "approved_licenses": ["apache-2.0"], "voice": True,
            "site_path": str(site), "roots": ["pkgc"], "wheel_caches": [],
            "probe_imports": ["pkgc"], "pip": pip, "platform": dict(PLAT),
        })
        self.assertTrue(out.is_file())
        self.assertTrue(prepared["wheels_complete"])
        venv = self.dst_home / "venv"
        installed = transfer.run_transfer_request(self.dst_home, {
            "action": "install", "bundle": str(out),
            "approved_licenses": ["apache-2.0"], "venv": str(venv),
            "platform": dict(PLAT)})
        self.assertTrue((self.dst_home / "assistant" / "imports" / "everyday" /
                         "transfer-lock.json").exists())
        proc = subprocess.run(
            [str(venv / "bin" / "python"), "-c", "import pkgc; print(pkgc.VALUE)"],
            capture_output=True, text=True, timeout=60)
        self.assertEqual(proc.stdout.strip(), "pkgc")
        self.assertIn("apache-2.0", installed["licenses"])

    def test_prepare_rejects_missing_approval_and_missing_lock(self) -> None:
        with self.assertRaisesRegex(transfer.TransferError, "approval"):
            transfer.run_transfer_request(self.src_home, {
                "action": "prepare", "pair_ids": ["everyday"],
                "output": str(self.root / "x.zip")})
        with self.assertRaisesRegex(transfer.TransferError, "pair lock"):
            transfer.run_transfer_request(self.src_home, {
                "action": "prepare", "pair_ids": ["ghost"],
                "output": str(self.root / "x.zip"),
                "approved_licenses": ["apache-2.0"]})


class CliMain(Base):
    def test_inspect_cli_prints_json(self) -> None:
        import contextlib
        import io
        self.export()
        buf, err = io.StringIO(), io.StringIO()
        with contextlib.redirect_stdout(buf), contextlib.redirect_stderr(err):
            rc = transfer.main(["inspect", "--bundle", str(self.bundle_path())])
        self.assertEqual(rc, 0)
        self.assertIn("bundle_id", json.loads(buf.getvalue()))

    def test_cli_missing_bundle_exits_one(self) -> None:
        import contextlib
        import io
        buf, err = io.StringIO(), io.StringIO()
        with contextlib.redirect_stdout(buf), contextlib.redirect_stderr(err):
            rc = transfer.main(["inspect", "--bundle", str(self.root / "gone.zip")])
        self.assertEqual(rc, 1)

    def test_cli_prepare_requires_explicit_approval(self) -> None:
        import contextlib
        import io
        (self.src_home / "assistant" / "pair-locks").mkdir(parents=True)
        (self.src_home / "assistant" / "pair-locks" / "everyday.json").write_text(
            json.dumps(self.lock))
        buf, err = io.StringIO(), io.StringIO()
        with contextlib.redirect_stdout(buf), contextlib.redirect_stderr(err):
            rc = transfer.main(["prepare", "--home", str(self.src_home),
                                "--pair", "everyday",
                                "--output", str(self.root / "x.zip")])
        self.assertEqual(rc, 1)


def manifest_bundle_id(path: Path) -> str:
    with zipfile.ZipFile(path) as zf:
        return json.loads(zf.read(transfer.MANIFEST_NAME))["bundle_id"]


if __name__ == "__main__":
    unittest.main(verbosity=2)
