// Copyright © 2026 Joshua Warren / mlx-omarchy contributors.
// SPDX-License-Identifier: MIT

// H13 compiler-package -> strict bundle-contract boundary tests
// (plan sections 46/48/62, host only, no device access).
//
// The payloads here are the REAL bytes emitted by the pinned compiler
// mil-hwx-compiler a0ce354cf800011a84420da4e12013eb8140b2a5 for the known
// conv+relu graph (qualification package h13-qualification/conv_relu,
// 4097 programs; both program shapes are embedded below and their
// provenance is receipts/fixtures/h13-conv-relu-boundary/README.md).
//
// What these tests pin:
//   1. Real H13 payloads satisfy every libane ANEC header check, the
//      kernel-placement guard (align16(task_size) == compiler
//      constantOffset), and the full v2 manifest/ANEC cross-check.
//   2. The §62 blocker, exactly: the honest per-program v2 manifest is
//      rejected by parse_ane_manifest at exactly one field — the single
//      workspace tensor must have a positive byte_size, but the honest
//      package-wide value is 0 (tiles[3] == 0 in every payload; the
//      package schema has no workspace concept at all). This is
//      discovery receipt §8.6; the wording decision belongs to the
//      bundle-schema owner. When that decision lands, the boundary case
//      below flips and the adapter becomes implementable. Until then no
//      adapter may fabricate a positive value.
//   3. Fail-closed identity handling: with the workspace satisfiable, an
//      empty firmware window is still rejected before anything else —
//      identity is required, and the validator cannot verify any range
//      it is given (§8.7), which is why firmware identity stays an
//      operator-verified required input rather than a default.

#define DOCTEST_CONFIG_IMPLEMENT_WITH_MAIN
#include "doctest/doctest.h"

#include "mlx/backend/omarchy/ane/bundle.h"
#include "mlx/backend/omarchy/ane/manifest.h"

#include <cstdint>
#include <filesystem>
#include <fstream>
#include <stdexcept>
#include <string>
#include <vector>

using namespace mlx::core::omarchy::ane;

namespace {

// Real program-0.anec: conv, encoder apple-parity-conv, 12928 bytes.
const char* kProgram0Base64 =     "gCIAAAAAAAB0AgAAAQAAAHQCAAAAAAAAACAAAAAAAAABAAAAAQAAAAEAAAAAAAAAAAAAAAAAAAAgAAAAIAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAABAAAAAAAAA"
    "AEAAAAAAAAAAQAAAAAAAAAAAIAAAAAAAAIAAAAAAAAAAAQAAAAAAAABAAAAAAAAAAEAAAAAAAAAAQAAAAAAAAAAAIAAAAAAAAIAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIeAAAAKgQAAAAAAABq+P8AAAAAAACYADAA"
    "AAAAJFACBSEAAAAA+AH0QAAAAAAAAACBAAAAgQAAAIEAAACBAAAAgQAAAIEAAACBAAAAgQAAAIEAAACBAAAAgQAAAIEAAACBAAAA"
    "gQAAAIEAAACBAAAAAAAAAAACAAAABAAAAAYAAAAIAAAACgAAAAwAAAAOAAAAEAAAABIAAAAUAAAAFgAAABgAAAAaAAAAHAAAAB4A"
    "AAACAAAAAgAAAAIAAAACAAAAAgAAAAIAAAACAAAAAgAAAAIAAAACAAAAAgAAAAIAAAACAAAAAgAAAAIAAAACAACAAAAAgAAAAIAA"
    "AACAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAABAAAAAQAAAAEAAAAAAAAA8QABAAAEAAAAiAAAAQAAAAEAAAABAAEAAAQAAACGoAFBB"
    "IAAAAQABAEAAAAAAAAAAAAAAAAEAIQAAABAAAAAAAAA4AWyBOAMAgIgAAAAAAACAAAAAACAAAAAACAAAAAgAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAADEgAAEAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEgA"
    "RAAAAAByAVAAAAAAAIAAAAAAIAAAACAAAAAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHoBUAAAAAgAAAAAAAAAAAAAAAAAAAAAAACI"
    "AAwAAAAAAAAAAAAAAAAAAAAAAMgAEIIAAAAAHBAAAAAAAAAAAAAAPAAAAHgBGMEAAAQAAAAAgAAAAAAgAAAAAAgAAAAIADEgMAEA"
    "AAAAAAAAAAAAAAAAtgC0ALAAAAC0ALAAAAAwALAAAAAwADQAAAAwADQANgAwADQANgC2ADQANgC2ALQANgC2ALQAsAC2ALQAsAAA"
    "ALQAsAAAADAAsAAAADAANAAAADAANAA2ADAANAA2ALYANAA2ALYAtAA2ALYAtACwALYAtACwAAAAtACwAAAAMACwAAAAMAA0AAAA"
    "MAA0ADYAMAA0ADYAtgA0ADYAtgC0ADYAtgC0ALAAtgC0ALAAAAC0ALAAAAAwALAAAAAwADQAAAAwADQANgAwADQANgC2ADQANgC2"
    "ALQANgC2ALQAsAC2ALQAsAAAALQAsAAAADAAsAAAADAANAAAADAANAA2ADAANAA2ALYANAA2ALYAtAA2ALYAtACwALYAtACwAAAA"
    "tACwAAAAMACwAAAAMAA0AAAAMAA0ADYAMAA0ADYAtgA0ADYAtgC0ADYAtgC0ALAAtgC0ALAAAAC0ALAAAAAwALAAAAAwADQAAAAw"
    "ADQANgAwADQANgC2ADQANgC2ALQANgC2ALQAsAC2ALQAsAAAALQAsAAAADAAsAAAADAANAAAADAANAA2ADAANAA2ALYANAA2ALYA"
    "tAA2ALYAtACwALYAtACwAAAAtACwAAAAMACwAAAAMAA0AAAAMAA0ADYAMAA0ADYAtgA0ADYAtgC0ADYAtgC0ALAAtgC0ALAAAAAw"
    "ADQANgC2ADQANgC2ALQANgC2ALQAsAC2ALQAsAAAALQAsAAAADAAsAAAADAANAAAADAANAA2ADAANAA2ALYANAA2ALYAtAA2ALYA"
    "tACwALYAtACwAAAAtACwAAAAMACwAAAAMAA0AAAAMAA0ADYAMAA0ADYAtgA0ADYAtgC0ADYAtgC0ALAAtgC0ALAAAAC0ALAAAAAw"
    "ALAAAAAwADQAAAAwADQANgAwADQANgC2ADQANgC2ALQANgC2ALQAsAC2ALQAsAAAALQAsAAAADAAsAAAADAANAAAADAANAA2ADAA"
    "NAA2ALYANAA2ALYAtAA2ALYAtACwALYAtACwAAAAtACwAAAAMACwAAAAMAA0AAAAMAA0ADYAMAA0ADYAtgA0ADYAtgC0ADYAtgC0"
    "ALAAtgC0ALAAAAC0ALAAAAAwALAAAAAwADQAAAAwADQANgAwADQANgC2ADQANgC2ALQANgC2ALQAsAC2ALQAsAAAALQAsAAAADAA"
    "sAAAADAANAAAADAANAA2ADAANAA2ALYANAA2ALYAtAA2ALYAtACwALYAtACwAAAAtACwAAAAMACwAAAAMAA0AAAAMAA0ADYAMAA0"
    "ADYAtgA0ADYAtgC0ADYAtgC0ALAAtgC0ALAAAAC0ALAAAAAwALAAAAAwADQAAAAwADQANgAwADQANgC2ALQAsAAAADAAsAAAADAA"
    "NAAAADAANAA2ADAANAA2ALYANAA2ALYAtAA2ALYAtACwALYAtACwAAAAtACwAAAAMACwAAAAMAA0AAAAMAA0ADYAMAA0ADYAtgA0"
    "ADYAtgC0ADYAtgC0ALAAtgC0ALAAAAC0ALAAAAAwALAAAAAwADQAAAAwADQANgAwADQANgC2ADQANgC2ALQANgC2ALQAsAC2ALQA"
    "sAAAALQAsAAAADAAsAAAADAANAAAADAANAA2ADAANAA2ALYANAA2ALYAtAA2ALYAtACwALYAtACwAAAAtACwAAAAMACwAAAAMAA0"
    "AAAAMAA0ADYAMAA0ADYAtgA0ADYAtgC0ADYAtgC0ALAAtgC0ALAAAAC0ALAAAAAwALAAAAAwADQAAAAwADQANgAwADQANgC2ADQA"
    "NgC2ALQANgC2ALQAsAC2ALQAsAAAALQAsAAAADAAsAAAADAANAAAADAANAA2ADAANAA2ALYANAA2ALYAtAA2ALYAtACwALYAtACw"
    "AAAAtACwAAAAMACwAAAAMAA0AAAAMAA0ADYAMAA0ADYAtgA0ADYAtgC0ADYAtgC0ALAAtgC0ALAAAAC0ALAAAAAwALAAAAAwADQA"
    "AAAwADQANgAwADQANgC2ADQANgC2ALQANgC2ALQAsAC2ALQAsAAAALQAsAAAADAANAA2ALYAtAA2ALYAtACwALYAtACwAAAAtACw"
    "AAAAMACwAAAAMAA0AAAAMAA0ADYAMAA0ADYAtgA0ADYAtgC0ADYAtgC0ALAAtgC0ALAAAAC0ALAAAAAwALAAAAAwADQAAAAwADQA"
    "NgAwADQANgC2ADQANgC2ALQANgC2ALQAsAC2ALQAsAAAALQAsAAAADAAsAAAADAANAAAADAANAA2ADAANAA2ALYANAA2ALYAtAA2"
    "ALYAtACwALYAtACwAAAAtACwAAAAMACwAAAAMAA0AAAAMAA0ADYAMAA0ADYAtgA0ADYAtgC0ADYAtgC0ALAAtgC0ALAAAAC0ALAA"
    "AAAwALAAAAAwADQAAAAwADQANgAwADQANgC2ADQANgC2ALQANgC2ALQAsAC2ALQAsAAAALQAsAAAADAAsAAAADAANAAAADAANAA2"
    "ADAANAA2ALYANAA2ALYAtAA2ALYAtACwALYAtACwAAAAtACwAAAAMACwAAAAMAA0AAAAMAA0ADYAMAA0ADYAtgA0ADYAtgC0ADYA"
    "tgC0ALAAtgC0ALAAAAC0ALAAAAAwALAAAAAwADQAAAAwADQANgAwADQANgC2ADQANgC2ALQANgC2ALQAsAC2ALQAsAAAALQAsAAA"
    "ADAAsAAAADAANAAAADAANAA2ADAANAA2ALYANAA2ALYAtACwAAAAMAA0AAAAMAA0ADYAMAA0ADYAtgA0ADYAtgC0ADYAtgC0ALAA"
    "tgC0ALAAAAC0ALAAAAAwALAAAAAwADQAAAAwADQANgAwADQANgC2ADQANgC2ALQANgC2ALQAsAC2ALQAsAAAALQAsAAAADAAsAAA"
    "ADAANAAAADAANAA2ADAANAA2ALYANAA2ALYAtAA2ALYAtACwALYAtACwAAAAtACwAAAAMACwAAAAMAA0AAAAMAA0ADYAMAA0ADYA"
    "tgA0ADYAtgC0ADYAtgC0ALAAtgC0ALAAAAC0ALAAAAAwALAAAAAwADQAAAAwADQANgAwADQANgC2ADQANgC2ALQANgC2ALQAsAC2"
    "ALQAsAAAALQAsAAAADAAsAAAADAANAAAADAANAA2ADAANAA2ALYANAA2ALYAtAA2ALYAtACwALYAtACwAAAAtACwAAAAMACwAAAA"
    "MAA0AAAAMAA0ADYAMAA0ADYAtgA0ADYAtgC0ADYAtgC0ALAAtgC0ALAAAAC0ALAAAAAwALAAAAAwADQAAAAwADQANgAwADQANgC2"
    "ADQANgC2ALQANgC2ALQAsAC2ALQAsAAAALQAsAAAADAAsAAAADAANAAAADAANAA2ADAANAA2ALYANAA2ALYAtAA2ALYAtACwALYA"
    "tACwAAAAtACwAAAAMACwAAAAMAA0ADYAtgC0ALAAtgC0ALAAAAC0ALAAAAAwALAAAAAwADQAAAAwADQANgAwADQANgC2ADQANgC2"
    "ALQANgC2ALQAsAC2ALQAsAAAALQAsAAAADAAsAAAADAANAAAADAANAA2ADAANAA2ALYANAA2ALYAtAA2ALYAtACwALYAtACwAAAA"
    "tACwAAAAMACwAAAAMAA0AAAAMAA0ADYAMAA0ADYAtgA0ADYAtgC0ADYAtgC0ALAAtgC0ALAAAAC0ALAAAAAwALAAAAAwADQAAAAw"
    "ADQANgAwADQANgC2ADQANgC2ALQANgC2ALQAsAC2ALQAsAAAALQAsAAAADAAsAAAADAANAAAADAANAA2ADAANAA2ALYANAA2ALYA"
    "tAA2ALYAtACwALYAtACwAAAAtACwAAAAMACwAAAAMAA0AAAAMAA0ADYAMAA0ADYAtgA0ADYAtgC0ADYAtgC0ALAAtgC0ALAAAAC0"
    "ALAAAAAwALAAAAAwADQAAAAwADQANgAwADQANgC2ADQANgC2ALQANgC2ALQAsAC2ALQAsAAAALQAsAAAADAAsAAAADAANAAAADAA"
    "NAA2ADAANAA2ALYANAA2ALYAtAA2ALYAtACwALYAtACwAAAAtACwAAAAMACwAAAAMAA0AAAAMAA0ADYAMAA0ADYAtgA0ADYAtgC0"
    "ADYAtgC0ALAAAAAwADQANgAwADQANgC2ADQANgC2ALQANgC2ALQAsAC2ALQAsAAAALQAsAAAADAAsAAAADAANAAAADAANAA2ADAA"
    "NAA2ALYANAA2ALYAtAA2ALYAtACwALYAtACwAAAAtACwAAAAMACwAAAAMAA0AAAAMAA0ADYAMAA0ADYAtgA0ADYAtgC0ADYAtgC0"
    "ALAAtgC0ALAAAAC0ALAAAAAwALAAAAAwADQAAAAwADQANgAwADQANgC2ADQANgC2ALQANgC2ALQAsAC2ALQAsAAAALQAsAAAADAA"
    "sAAAADAANAAAADAANAA2ADAANAA2ALYANAA2ALYAtAA2ALYAtACwALYAtACwAAAAtACwAAAAMACwAAAAMAA0AAAAMAA0ADYAMAA0"
    "ADYAtgA0ADYAtgC0ADYAtgC0ALAAtgC0ALAAAAC0ALAAAAAwALAAAAAwADQAAAAwADQANgAwADQANgC2ADQANgC2ALQANgC2ALQA"
    "sAC2ALQAsAAAALQAsAAAADAAsAAAADAANAAAADAANAA2ADAANAA2ALYANAA2ALYAtAA2ALYAtACwALYAtACwAAAAtACwAAAAMACw"
    "AAAAMAA0AAAAMAA0ADYAMAA0ADYAtgA0ADYAtgC0ADYAtgC0ALAAtgC0ALAAAAC0ALAAAAAwALAAAAAwADQAAAAwADQANgC2ALQA"
    "sAAAALQAsAAAADAAsAAAADAANAAAADAANAA2ADAANAA2ALYANAA2ALYAtAA2ALYAtACwALYAtACwAAAAtACwAAAAMACwAAAAMAA0"
    "AAAAMAA0ADYAMAA0ADYAtgA0ADYAtgC0ADYAtgC0ALAAtgC0ALAAAAC0ALAAAAAwALAAAAAwADQAAAAwADQANgAwADQANgC2ADQA"
    "NgC2ALQANgC2ALQAsAC2ALQAsAAAALQAsAAAADAAsAAAADAANAAAADAANAA2ADAANAA2ALYANAA2ALYAtAA2ALYAtACwALYAtACw"
    "AAAAtACwAAAAMACwAAAAMAA0AAAAMAA0ADYAMAA0ADYAtgA0ADYAtgC0ADYAtgC0ALAAtgC0ALAAAAC0ALAAAAAwALAAAAAwADQA"
    "AAAwADQANgAwADQANgC2ADQANgC2ALQANgC2ALQAsAC2ALQAsAAAALQAsAAAADAAsAAAADAANAAAADAANAA2ADAANAA2ALYANAA2"
    "ALYAtAA2ALYAtACwALYAtACwAAAAtACwAAAAMACwAAAAMAA0AAAAMAA0ADYAMAA0ADYAtgA0ADYAtgC0ADYAtgC0ALAAtgC0ALAA"
    "AAC0ALAAAAAwALAAAAAwADQAAAAwADQANgAwADQANgC2ADQANgC2ALQANgC2ALQAsAC2ALQAsAAAADAANAA2ALYANAA2ALYAtAA2"
    "ALYAtACwALYAtACwAAAAtACwAAAAMACwAAAAMAA0AAAAMAA0ADYAMAA0ADYAtgA0ADYAtgC0ADYAtgC0ALAAtgC0ALAAAAC0ALAA"
    "AAAwALAAAAAwADQAAAAwADQANgAwADQANgC2ADQANgC2ALQANgC2ALQAsAC2ALQAsAAAALQAsAAAADAAsAAAADAANAAAADAANAA2"
    "ADAANAA2ALYANAA2ALYAtAA2ALYAtACwALYAtACwAAAAtACwAAAAMACwAAAAMAA0AAAAMAA0ADYAMAA0ADYAtgA0ADYAtgC0ADYA"
    "tgC0ALAAtgC0ALAAAAC0ALAAAAAwALAAAAAwADQAAAAwADQANgAwADQANgC2ADQANgC2ALQANgC2ALQAsAC2ALQAsAAAALQAsAAA"
    "ADAAsAAAADAANAAAADAANAA2ADAANAA2ALYANAA2ALYAtAA2ALYAtACwALYAtACwAAAAtACwAAAAMACwAAAAMAA0AAAAMAA0ADYA"
    "MAA0ADYAtgA0ADYAtgC0ADYAtgC0ALAAtgC0ALAAAAC0ALAAAAAwALAAAAAwADQAAAAwADQANgAwADQANgC2ADQANgC2ALQANgC2"
    "ALQAsAC2ALQAsAAAALQAsAAAADAAsAAAADAANAAAADAANAA2ADAANAA2ALYAtACwAAAAMACwAAAAMAA0AAAAMAA0ADYAMAA0ADYA"
    "tgA0ADYAtgC0ADYAtgC0ALAAtgC0ALAAAAC0ALAAAAAwALAAAAAwADQAAAAwADQANgAwADQANgC2ADQANgC2ALQANgC2ALQAsAC2"
    "ALQAsAAAALQAsAAAADAAsAAAADAANAAAADAANAA2ADAANAA2ALYANAA2ALYAtAA2ALYAtACwALYAtACwAAAAtACwAAAAMACwAAAA"
    "MAA0AAAAMAA0ADYAMAA0ADYAtgA0ADYAtgC0ADYAtgC0ALAAtgC0ALAAAAC0ALAAAAAwALAAAAAwADQAAAAwADQANgAwADQANgC2"
    "ADQANgC2ALQANgC2ALQAsAC2ALQAsAAAALQAsAAAADAAsAAAADAANAAAADAANAA2ADAANAA2ALYANAA2ALYAtAA2ALYAtACwALYA"
    "tACwAAAAtACwAAAAMACwAAAAMAA0AAAAMAA0ADYAMAA0ADYAtgA0ADYAtgC0ADYAtgC0ALAAtgC0ALAAAAC0ALAAAAAwALAAAAAw"
    "ADQAAAAwADQANgAwADQANgC2ADQANgC2ALQANgC2ALQAsAC2ALQAsAAAALQAsAAAADAAsAAAADAANAAAADAANAA2ADAANAA2ALYA"
    "NAA2ALYAtAA2ALYAtACwALYAtACwAAAAtACwAAAAMAA0ADYAtgC0ADYAtgC0ALAAtgC0ALAAAAC0ALAAAAAwALAAAAAwADQAAAAw"
    "ADQANgAwADQANgC2ADQANgC2ALQANgC2ALQAsAC2ALQAsAAAALQAsAAAADAAsAAAADAANAAAADAANAA2ADAANAA2ALYANAA2ALYA"
    "tAA2ALYAtACwALYAtACwAAAAtACwAAAAMACwAAAAMAA0AAAAMAA0ADYAMAA0ADYAtgA0ADYAtgC0ADYAtgC0ALAAtgC0ALAAAAC0"
    "ALAAAAAwALAAAAAwADQAAAAwADQANgAwADQANgC2ADQANgC2ALQANgC2ALQAsAC2ALQAsAAAALQAsAAAADAAsAAAADAANAAAADAA"
    "NAA2ADAANAA2ALYANAA2ALYAtAA2ALYAtACwALYAtACwAAAAtACwAAAAMACwAAAAMAA0AAAAMAA0ADYAMAA0ADYAtgA0ADYAtgC0"
    "ADYAtgC0ALAAtgC0ALAAAAC0ALAAAAAwALAAAAAwADQAAAAwADQANgAwADQANgC2ADQANgC2ALQANgC2ALQAsAC2ALQAsAAAALQA"
    "sAAAADAAsAAAADAANAAAADAANAA2ADAANAA2ALYANAA2ALYAtAA2ALYAtACwALYAtACwAAAAtACwAAAAMACwAAAAMAA0AAAAMAA0"
    "ADYAMAA0ADYAtgA0ADYAtgC0ALAAAAAwADQAAAAwADQANgAwADQANgC2ADQANgC2ALQANgC2ALQAsAC2ALQAsAAAALQAsAAAADAA"
    "sAAAADAANAAAADAANAA2ADAANAA2ALYANAA2ALYAtAA2ALYAtACwALYAtACwAAAAtACwAAAAMACwAAAAMAA0AAAAMAA0ADYAMAA0"
    "ADYAtgA0ADYAtgC0ADYAtgC0ALAAtgC0ALAAAAC0ALAAAAAwALAAAAAwADQAAAAwADQANgAwADQANgC2ADQANgC2ALQANgC2ALQA"
    "sAC2ALQAsAAAALQAsAAAADAAsAAAADAANAAAADAANAA2ADAANAA2ALYANAA2ALYAtAA2ALYAtACwALYAtACwAAAAtACwAAAAMACw"
    "AAAAMAA0AAAAMAA0ADYAMAA0ADYAtgA0ADYAtgC0ADYAtgC0ALAAtgC0ALAAAAC0ALAAAAAwALAAAAAwADQAAAAwADQANgAwADQA"
    "NgC2ADQANgC2ALQANgC2ALQAsAC2ALQAsAAAALQAsAAAADAAsAAAADAANAAAADAANAA2ADAANAA2ALYANAA2ALYAtAA2ALYAtACw"
    "ALYAtACwAAAAtACwAAAAMACwAAAAMAA0AAAAMAA0ADYAMAA0ADYAtgA0ADYAtgC0ADYAtgC0ALAAtgC0ALAAAAC0ALAAAAAwALAA"
    "AAAwADQANgC2ALQAsAC2ALQAsAAAALQAsAAAADAAsAAAADAANAAAADAANAA2ADAANAA2ALYANAA2ALYAtAA2ALYAtACwALYAtACw"
    "AAAAtACwAAAAMACwAAAAMAA0AAAAMAA0ADYAMAA0ADYAtgA0ADYAtgC0ADYAtgC0ALAAtgC0ALAAAAC0ALAAAAAwALAAAAAwADQA"
    "AAAwADQANgAwADQANgC2ADQANgC2ALQANgC2ALQAsAC2ALQAsAAAALQAsAAAADAAsAAAADAANAAAADAANAA2ADAANAA2ALYANAA2"
    "ALYAtAA2ALYAtACwALYAtACwAAAAtACwAAAAMACwAAAAMAA0AAAAMAA0ADYAMAA0ADYAtgA0ADYAtgC0ADYAtgC0ALAAtgC0ALAA"
    "AAC0ALAAAAAwALAAAAAwADQAAAAwADQANgAwADQANgC2ADQANgC2ALQANgC2ALQAsAC2ALQAsAAAALQAsAAAADAAsAAAADAANAAA"
    "ADAANAA2ADAANAA2ALYANAA2ALYAtAA2ALYAtACwALYAtACwAAAAtACwAAAAMACwAAAAMAA0AAAAMAA0ADYAMAA0ADYAtgA0ADYA"
    "tgC0ADYAtgC0ALAAtgC0ALAAAAC0ALAAAAAwALAAAAAwADQAAAAwADQANgAwADQANgC2ADQANgC2ALQANgC2ALQAsAAAADAANAA2"
    "ADAANAA2ALYANAA2ALYAtAA2ALYAtACwALYAtACwAAAAtACwAAAAMACwAAAAMAA0AAAAMAA0ADYAMAA0ADYAtgA0ADYAtgC0ADYA"
    "tgC0ALAAtgC0ALAAAAC0ALAAAAAwALAAAAAwADQAAAAwADQANgAwADQANgC2ADQANgC2ALQANgC2ALQAsAC2ALQAsAAAALQAsAAA"
    "ADAAsAAAADAANAAAADAANAA2ADAANAA2ALYANAA2ALYAtAA2ALYAtACwALYAtACwAAAAtACwAAAAMACwAAAAMAA0AAAAMAA0ADYA"
    "MAA0ADYAtgA0ADYAtgC0ADYAtgC0ALAAtgC0ALAAAAC0ALAAAAAwALAAAAAwADQAAAAwADQANgAwADQANgC2ADQANgC2ALQANgC2"
    "ALQAsAC2ALQAsAAAALQAsAAAADAAsAAAADAANAAAADAANAA2ADAANAA2ALYANAA2ALYAtAA2ALYAtACwALYAtACwAAAAtACwAAAA"
    "MACwAAAAMAA0AAAAMAA0ADYAMAA0ADYAtgA0ADYAtgC0ADYAtgC0ALAAtgC0ALAAAAC0ALAAAAAwALAAAAAwADQAAAAwADQANgAw"
    "ADQANgC2ADQANgC2ALQANgC2ALQAsAC2ALQAsAAAALQAsAAAADAAsAAAADAANAAAADAANAA2ALYAtACwAAAAtACwAAAAMACwAAAA"
    "MAA0AAAAMAA0ADYAMAA0ADYAtgA0ADYAtgC0ADYAtgC0ALAAtgC0ALAAAAC0ALAAAAAwALAAAAAwADQAAAAwADQANgAwADQANgC2"
    "ADQANgC2ALQANgC2ALQAsAC2ALQAsAAAALQAsAAAADAAsAAAADAANAAAADAANAA2ADAANAA2ALYANAA2ALYAtAA2ALYAtACwALYA"
    "tACwAAAAtACwAAAAMACwAAAAMAA0AAAAMAA0ADYAMAA0ADYAtgA0ADYAtgC0ADYAtgC0ALAAtgC0ALAAAAC0ALAAAAAwALAAAAAw"
    "ADQAAAAwADQANgAwADQANgC2ADQANgC2ALQANgC2ALQAsAC2ALQAsAAAALQAsAAAADAAsAAAADAANAAAADAANAA2ADAANAA2ALYA"
    "NAA2ALYAtAA2ALYAtACwALYAtACwAAAAtACwAAAAMACwAAAAMAA0AAAAMAA0ADYAMAA0ADYAtgA0ADYAtgC0ADYAtgC0ALAAtgC0"
    "ALAAAAC0ALAAAAAwALAAAAAwADQAAAAwADQANgAwADQANgC2ADQANgC2ALQANgC2ALQAsAC2ALQAsAAAALQAsAAAADAAsAAAADAA"
    "NAAAADAANAA2ADAANAA2ALYANAA2ALYAtAA2ALYAtACwALYAtACwAAAAMAA0ADYAtgA0ADYAtgC0ADYAtgC0ALAAtgC0ALAAAAC0"
    "ALAAAAAwALAAAAAwADQAAAAwADQANgAwADQANgC2ADQANgC2ALQANgC2ALQAsAC2ALQAsAAAALQAsAAAADAAsAAAADAANAAAADAA"
    "NAA2ADAANAA2ALYANAA2ALYAtAA2ALYAtACwALYAtACwAAAAtACwAAAAMACwAAAAMAA0AAAAMAA0ADYAMAA0ADYAtgA0ADYAtgC0"
    "ADYAtgC0ALAAtgC0ALAAAAC0ALAAAAAwALAAAAAwADQAAAAwADQANgAwADQANgC2ADQANgC2ALQANgC2ALQAsAC2ALQAsAAAALQA"
    "sAAAADAAsAAAADAANAAAADAANAA2ADAANAA2ALYANAA2ALYAtAA2ALYAtACwALYAtACwAAAAtACwAAAAMACwAAAAMAA0AAAAMAA0"
    "ADYAMAA0ADYAtgA0ADYAtgC0ADYAtgC0ALAAtgC0ALAAAAC0ALAAAAAwALAAAAAwADQAAAAwADQANgAwADQANgC2ADQANgC2ALQA"
    "NgC2ALQAsAC2ALQAsAAAALQAsAAAADAAsAAAADAANAAAADAANAA2ADAANAA2ALYANAA2ALYAtAA2ALYAtACwALYAtACwAAAAtACw"
    "AAAAMACwAAAAMAA0AAAAMAA0ADYAMAA0ADYAtg==";
// Real program-1.anec: first maximum slice, encoder h13-source-qualified,
// 4736 bytes.
const char* kProgram1Base64 =     "gAIAAAAAAAB0AgAAAQAAAHQCAAAAAAAAAAAAAAAAAAACAAAAAQAAAAEAAAAAAAAAAAAAAAAAAAABAAAAAQAAAAEAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAABAAAAAAAAA"
    "AAEAAAAAAAAAAQAAAAAAAABAAAAAAAAAAEAAAAAAAAAAAQAAAAAAAABAAAAAAAAAAAEAAAAAAAAAAQAAAAAAAABAAAAAAAAAAEAA"
    "AAAAAAAAAQAAAAAAAABAAAAAAAAAAAEAAAAAAAAAAQAAAAAAAABAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAIAAAAAIgQAAAAAAABq+P8AAAAAAACYADAA"
    "AAAAZkkCAAAAAAAA+AH0AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA8AQABAAEAAAAqAAAAQAAAAEAAAAABAAEAAQAAACGgAFBB"
    "IAAAAQABAAEAAAAEAAAAAAAAADMAAAAAAAAAAAAAAAA4AWyBOAMAgDgDAAAAAABAAAAAQAAAAAAQAAAAAAAAAAAAAEAAAABAAAAA"
    "ABAAAAAAAAAAAAAAAAAAADEgAAEwIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEgA"
    "RAAAAAByAVABAAAAABAAAAAgBAAAAAQAAAAEAABABAAAEAAAACAEAAAABAAAAAQAAHoBUABgCAAAAAAAAAAAAAAAAAAAAAAAAACI"
    "AAwIAAgAAAAAPAAAADwAAIA/AMgAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAHgBGMEAAAQAAAAAQAAAAEAAAAAAEAAAAAAAADEgAAEA"
    "AAAAAAAAAAAAAAA=";

const char* kProgram0Sha256 =
    "63462dece46ebcd100b3785be09979786c969d7add75b212902344418fcb7123";
const char* kProgram1Sha256 =
    "3d73787c1fc04842da72bb6e1a1930ffa1d3c7b7280ab7d838add2da2edfba22";
// sha256 of tests/fixtures/conv_relu.mil inside the hash-verified pinned
// compiler source tree. Per ane_export.py precedent, graph_hash is the
// digest of the source graph artifact.
const char* kSourceMilSha256 =
    "cc204fd0252b16fe514970fcd82abde15600303f8355718984ae8ba4ddab7cf8";
// The pinned compiler identity (ane-compiler.lock).
const char* kCompilerCommit = "a0ce354cf800011a84420da4e12013eb8140b2a5";

std::string base64_decode(const char* encoded) {
  static const std::string alphabet =
      "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/";
  std::string text(encoded);
  std::vector<uint8_t> decoded;
  int phase = 0;
  uint32_t accumulator = 0;
  for (char c : text) {
    if (c == '\n' || c == '\r' || c == ' ') {
      continue;
    }
    if (c == '=') {
      break;
    }
    size_t value = alphabet.find(c);
    if (value == std::string::npos) {
      break;
    }
    accumulator = (accumulator << 6) | static_cast<uint32_t>(value);
    if (++phase == 4) {
      decoded.push_back(static_cast<uint8_t>((accumulator >> 16) & 0xff));
      decoded.push_back(static_cast<uint8_t>((accumulator >> 8) & 0xff));
      decoded.push_back(static_cast<uint8_t>(accumulator & 0xff));
      phase = 0;
      accumulator = 0;
    }
  }
  // Final unpadded quantum: 3 chars carry 2 bytes, 2 chars carry 1.
  if (phase == 3) {
    decoded.push_back(static_cast<uint8_t>((accumulator >> 10) & 0xff));
    decoded.push_back(static_cast<uint8_t>((accumulator >> 2) & 0xff));
  } else if (phase == 2) {
    decoded.push_back(static_cast<uint8_t>((accumulator >> 4) & 0xff));
  }
  return std::string(decoded.begin(), decoded.end());
}

// Same temp-directory pattern as test_bundle.cpp.
class TempDir {
 public:
  TempDir() {
    namespace fs = std::filesystem;
    fs::path base = fs::temp_directory_path() / "mlx-omarchy-ane-h13-boundary";
    fs::create_directories(base);
    for (int attempt = 0; attempt < 64; ++attempt) {
      fs::path candidate =
          base / ("case-" + std::to_string(attempt) + "-" +
                  std::to_string(::getpid()));
      std::error_code error;
      if (fs::create_directory(candidate, error) && !error) {
        path_ = candidate;
        return;
      }
    }
    throw std::runtime_error("cannot create temp directory");
  }
  ~TempDir() {
    std::error_code error;
    std::filesystem::remove_all(path_, error);
  }
  const std::filesystem::path& path() const {
    return path_;
  }

 private:
  std::filesystem::path path_;
};

void write_file(const std::filesystem::path& path, const std::string& content) {
  std::ofstream out(path, std::ios::binary | std::ios::trunc);
  out << content;
  REQUIRE(out.good());
}

// Writes one program payload and returns the bundle directory containing
// only manifest.json and that payload.
std::filesystem::path write_program_bundle(
    const TempDir& temp,
    const char* program_base64,
    const char* program_path,
    const std::string& manifest_json) {
  namespace fs = std::filesystem;
  static int counter = 0;
  fs::path dir = temp.path() / ("bundle-" + std::to_string(counter++));
  fs::create_directories(dir);
  write_file(dir / program_path, base64_decode(program_base64));
  write_file(dir / "manifest.json", manifest_json);
  return dir;
}

// Renders the per-program v2 manifest exactly as an adapter would: every
// field derived from real package data (compiler manifest record + ANEC
// header), with two deliberate parameters:
//   - workspace_bytes 0 = the honest value (the §62 boundary), or a
//     diagnostic positive value, always commented as such;
//   - firmware min/max = the operator-verified required input. The empty
//     pair is used only where a test proves identity stays fail-closed.
std::string render_conv_manifest(uint64_t workspace_bytes) {
  std::string json = "{\n";
  json += "  \"manifest_version\": 2,\n";
  json += "  \"name\": \"conv_relu\",\n";
  json += std::string("  \"graph_hash\": \"") + kSourceMilSha256 + "\",\n";
  json += "  \"task_descriptors\": 1,\n";
  json += "  \"inputs\": [\n";
  json += "    {\"name\": \"x\", \"index\": 5, \"dtype\": \"float16\",";
  json += " \"shape\": [1, 64, 64, 64],";
  json += " \"byte_size\": 524288, \"stride\": 524288}\n";
  json += "  ],\n";
  json += "  \"outputs\": [\n";
  json += "    {\"name\": \"c0\", \"index\": 4, \"dtype\": \"float16\",";
  json += " \"shape\": [1, 64, 64, 64],";
  json += " \"byte_size\": 524288, \"stride\": 524288}\n";
  json += "  ],\n";
  json += "  \"state\": [],\n";
  // Honest H13 value is byte_size 0: no channel-3 surface exists in the
  // payload (tiles[3] == 0) and the package schema has no workspace
  // concept. Any positive value here is the fabrication §8.6 rules out.
  json += "  \"workspace\": [\n";
  json += "    {\"name\": \"workspace\", \"index\": 0, \"dtype\": \"uint8\",";
  json += " \"shape\": [" +
          std::to_string(workspace_bytes == 0 ? 1 : workspace_bytes) + "],";
  json += " \"byte_size\": " + std::to_string(workspace_bytes) + ",";
  json += " \"stride\": " + std::to_string(workspace_bytes) + "}\n";
  json += "  ],\n";
  json += "  \"payloads\": [\n";
  json += "    {\"role\": \"anec\", \"path\": \"program-0.anec\",";
  json += std::string(" \"sha256\": \"") + kProgram0Sha256 + "\",";
  json += " \"byte_size\": 12928}\n";
  json += "  ],\n";
  json += "  \"compiler\": {\"host_build\": \"linux-x86-64\",";
  json += std::string(" \"toolchain\": \"mil-hwxc ") + kCompilerCommit + "\",";
  json += " \"target\": \"h13\"},\n";
  json += "  \"firmware\": {\"min\": \"\", \"max\": \"\"},\n";
  json += "  \"provenance\": {\"source_repo\": \"joshuaswarren/mil-hwx-compiler\",";
  json += std::string(" \"source_commit\": \"") + kCompilerCommit + "\",";
  json += " \"exported_at\": \"2026-09-12\"},\n";
  json += "  \"release_asset\": {\"model\": \"conv_relu.mil\",";
  json += std::string(" \"model_sha256\": \"") + kSourceMilSha256 + "\"}\n";
  json += "}\n";
  return json;
}

std::string render_relu_slice_manifest(uint64_t workspace_bytes) {
  std::string json = "{\n";
  json += "  \"manifest_version\": 2,\n";
  json += "  \"name\": \"conv_relu\",\n";
  json += std::string("  \"graph_hash\": \"") + kSourceMilSha256 + "\",\n";
  json += "  \"task_descriptors\": 1,\n";
  json += "  \"inputs\": [\n";
  json += "    {\"name\": \"c0\", \"index\": 5, \"dtype\": \"float16\",";
  json += " \"shape\": [64], \"byte_size\": 128, \"stride\": 16384},\n";
  json += "    {\"name\": \"$h13.y.zero\", \"index\": 6, \"dtype\": \"float16\",";
  json += " \"shape\": [64], \"byte_size\": 128, \"stride\": 16384}\n";
  json += "  ],\n";
  json += "  \"outputs\": [\n";
  json += "    {\"name\": \"y\", \"index\": 4, \"dtype\": \"float16\",";
  json += " \"shape\": [64], \"byte_size\": 128, \"stride\": 16384}\n";
  json += "  ],\n";
  json += "  \"state\": [],\n";
  json += "  \"workspace\": [\n";
  json += "    {\"name\": \"workspace\", \"index\": 0, \"dtype\": \"uint8\",";
  json += " \"shape\": [" +
          std::to_string(workspace_bytes == 0 ? 1 : workspace_bytes) + "],";
  json += " \"byte_size\": " + std::to_string(workspace_bytes) + ",";
  json += " \"stride\": " + std::to_string(workspace_bytes) + "}\n";
  json += "  ],\n";
  json += "  \"payloads\": [\n";
  json += "    {\"role\": \"anec\", \"path\": \"program-1.anec\",";
  json += std::string(" \"sha256\": \"") + kProgram1Sha256 + "\",";
  json += " \"byte_size\": 4736}\n";
  json += "  ],\n";
  json += "  \"compiler\": {\"host_build\": \"linux-x86-64\",";
  json += std::string(" \"toolchain\": \"mil-hwxc ") + kCompilerCommit + "\",";
  json += " \"target\": \"h13\"},\n";
  json += "  \"firmware\": {\"min\": \"\", \"max\": \"\"},\n";
  json += "  \"provenance\": {\"source_repo\": \"joshuaswarren/mil-hwx-compiler\",";
  json += std::string(" \"source_commit\": \"") + kCompilerCommit + "\",";
  json += " \"exported_at\": \"2026-09-12\"},\n";
  json += "  \"release_asset\": {\"model\": \"conv_relu.mil\",";
  json += std::string(" \"model_sha256\": \"") + kSourceMilSha256 + "\"}\n";
  json += "}\n";
  return json;
}

// A format-valid firmware range for cases whose purpose requires manifest
// parsing to complete (payload verification). The validator cannot check
// the range's semantics (§8.7) — that is exactly why firmware identity
// stays an operator-verified required input. Diagnostic value only.
std::string with_diagnostic_firmware(std::string manifest) {
  const std::string empty = "\"firmware\": {\"min\": \"\", \"max\": \"\"},";
  const std::string range = "\"firmware\": {\"min\": \"0.0\", \"max\": \"0.0\"},";
  REQUIRE(manifest.find(empty) != std::string::npos);
  manifest.replace(manifest.find(empty), empty.size(), range);
  return manifest;
}

std::string load_error(const std::filesystem::path& dir) {
  try {
    load_bundle(dir);
  } catch (const AneBundleNotFound& error) {
    return std::string("not_found: ") + error.what();
  } catch (const std::exception& error) {
    return error.what();
  }
  return {};
}

} // namespace

TEST_CASE("real H13 qualification payloads satisfy the ANEC header contract") {
  TempDir temp;
  const std::string program0 = base64_decode(kProgram0Base64);
  const std::string program1 = base64_decode(kProgram1Base64);
  REQUIRE(program0.size() == 12928);
  REQUIRE(program1.size() == 4736);
  CHECK(sha256_hex(reinterpret_cast<const uint8_t*>(program0.data()),
                   program0.size()) == kProgram0Sha256);
  CHECK(sha256_hex(reinterpret_cast<const uint8_t*>(program1.data()),
                   program1.size()) == kProgram1Sha256);

  write_file(temp.path() / "program-0.anec", program0);
  write_file(temp.path() / "program-1.anec", program1);

  AneAnecHeader conv = parse_anec_header(temp.path() / "program-0.anec");
  CHECK(conv.payload_size == 8832);
  CHECK(conv.task_descriptor_size == 628);
  CHECK(conv.task_descriptor_count == 1);
  CHECK(conv.task_size == 628);
  CHECK(conv.kernel_size == 8192);
  CHECK(conv.source_count == 1);
  CHECK(conv.destination_count == 1);
  CHECK(conv.tiles[0] == 1);
  CHECK(conv.tiles[1] == 0);
  CHECK(conv.tiles[3] == 0);
  CHECK(conv.tiles[4] == 32);
  CHECK(conv.tiles[5] == 32);

  AneAnecHeader relu = parse_anec_header(temp.path() / "program-1.anec");
  CHECK(relu.payload_size == 640);
  CHECK(relu.task_descriptor_size == 628);
  CHECK(relu.task_descriptor_count == 1);
  CHECK(relu.task_size == 628);
  CHECK(relu.kernel_size == 0);
  CHECK(relu.source_count == 2);
  CHECK(relu.destination_count == 1);
  CHECK(relu.tiles[0] == 1);
  CHECK(relu.tiles[1] == 0);
  CHECK(relu.tiles[3] == 0);
  CHECK(relu.tiles[4] == 1);
  CHECK(relu.tiles[5] == 1);
  CHECK(relu.tiles[6] == 1);

  // Kernel-placement guard (discovery receipt §8.8): the device derives
  // the kernel at round16(task_size); the compiler manifest pins
  // constantOffset 640 for every program in the package. Both shapes
  // must agree or the device would read shifted weights.
  CHECK(((conv.task_size + 15) & ~15ull) == 640);
  CHECK(((relu.task_size + 15) & ~15ull) == 640);
}

TEST_CASE(
    "boundary: honest zero-workspace manifests are rejected at exactly "
    "the workspace positivity check (plan section 62 blocker)") {
  TempDir temp;
  auto conv_dir = write_program_bundle(
      temp, kProgram0Base64, "program-0.anec", render_conv_manifest(0));
  // The honest manifest dies in parse_ane_manifest before payload access:
  // workspace[0].byte_size 0 is the truthful value for this package, and
  // v2 requires it positive. This is the single-field blocker; it flips
  // when the §8.6 owner decision lands.
  CHECK(load_error(conv_dir)
        == std::string(
            "[omarchy-ane] manifest: field 'byte_size' must be positive."));

  auto relu_dir = write_program_bundle(
      temp, kProgram1Base64, "program-1.anec", render_relu_slice_manifest(0));
  CHECK(load_error(relu_dir)
        == std::string(
            "[omarchy-ane] manifest: field 'byte_size' must be positive."));
}

TEST_CASE(
    "fail-closed identity: empty firmware is rejected even when the "
    "workspace check is satisfiable") {
  TempDir temp;
  // Diagnostic manifests carry a positive workspace ONLY to reach the
  // firmware check past the workspace field. The value is the §8.6
  // fabrication pattern and is not a qualification of anything.
  auto dir = write_program_bundle(
      temp, kProgram0Base64, "program-0.anec", render_conv_manifest(16384));
  CHECK(load_error(dir)
        == std::string("[omarchy-ane] manifest: field 'min' must not be "
                       "empty."));
}

TEST_CASE(
    "boundary diagnostic: a fabricated workspace is the single field "
    "separating the honest manifest from full strict acceptance") {
  TempDir temp;
  // §62 boundary demonstration, not a qualification: workspace 16384 and
  // firmware "0.0"/"0.0" are deliberately minimal diagnostic values. The
  // acceptance proves every OTHER strict check (payload hashes, ANEC
  // header envelope, channel bindings, tile/NCHW geometry, compiler and
  // provenance identity) passes on real compiler bytes, isolating the
  // workspace wording as the only reconciliation gap. Host load
  // validation is not ANE execution, and this bundle must never reach a
  // device.
  std::string manifest = with_diagnostic_firmware(render_conv_manifest(16384));

  auto dir = write_program_bundle(temp, kProgram0Base64, "program-0.anec",
                                  manifest);
  AneBundle bundle = load_bundle(dir);
  CHECK(bundle.manifest.name == "conv_relu");
  CHECK(bundle.manifest.manifest_version == 2);
  CHECK(bundle.manifest.task_descriptors == 1);
  CHECK(bundle.manifest.inputs.size() == 1);
  CHECK(bundle.manifest.inputs[0].name == "x");
  CHECK(bundle.manifest.outputs.size() == 1);
  CHECK(bundle.manifest.outputs[0].name == "c0");
  CHECK(bundle.manifest.state.empty());
  CHECK(bundle.manifest.workspace.size() == 1);
  CHECK(bundle.manifest.workspace[0].byte_size == 16384);
  CHECK(bundle.anec.filename() == "program-0.anec");
  CHECK_FALSE(bundle.weights.has_value());
  CHECK(bundle.anec_header.payload_size == 8832);
  CHECK(bundle.anec_header.task_descriptor_count == 1);
  CHECK(bundle.anec_header.task_size == 628);
  CHECK(bundle.anec_header.kernel_size == 8192);
  CHECK(bundle.anec_header.source_count == 1);
  CHECK(bundle.anec_header.destination_count == 1);
  CHECK(bundle.anec_header.tiles[3] == 0);
  CHECK(bundle.anec_header.tiles[4] == 32);
  CHECK(bundle.anec_header.tiles[5] == 32);
}

TEST_CASE("payload mutations fail before any device surface") {
  TempDir temp;
  // load_bundle verifies manifest fields, then payload presence, byte
  // size, and digest, all before the ANEC header is parsed and long
  // before any mapping or submission. Both mutations must fail closed.
  const std::string good_digest =
      std::string("\"sha256\": \"") + kProgram0Sha256 + "\"";

  // Flip the last digest character to a different hex digit.
  std::string flipped(kProgram0Sha256);
  flipped.back() = flipped.back() == '3' ? '4' : '3';
  std::string bad_digest_manifest =
      with_diagnostic_firmware(render_conv_manifest(16384));
  bad_digest_manifest.replace(
      bad_digest_manifest.find(good_digest), good_digest.size(),
      std::string("\"sha256\": \"") + flipped + "\"");
  auto digest_dir = write_program_bundle(
      temp, kProgram0Base64, "program-0.anec", bad_digest_manifest);
  std::string message = load_error(digest_dir);
  CHECK(message.rfind(
            "[omarchy-ane] bundle: payload program-0.anec sha256 mismatch:",
            0)
        == 0);
  CHECK(message.find(flipped) != std::string::npos);
  CHECK(message.find(kProgram0Sha256) != std::string::npos);

  std::string bad_size_manifest =
      with_diagnostic_firmware(render_conv_manifest(16384));
  const std::string good_size = "\"byte_size\": 12928}";
  bad_size_manifest.replace(
      bad_size_manifest.find(good_size), good_size.size(),
      "\"byte_size\": 12929}");
  auto size_dir = write_program_bundle(temp, kProgram0Base64,
                                       "program-0.anec", bad_size_manifest);
  CHECK(load_error(size_dir)
        == std::string("[omarchy-ane] bundle: payload program-0.anec byte "
                       "size 12928 does not match manifest 12929."));
}
