#!/usr/bin/env bash
# Prepare the pinned external ANE compiler (plan sections 7-9, gate 46).
#
# Downloads the locked source archive, verifies its SHA-256 before anything
# is built, unpacks under the ignored .work subtree, builds the Linux
# compiler, runs the compiler's required host-side tests, and exposes a
# deterministic runnable binary path with the correct GNUstep runtime
# environment. Prints the actual provenance on success.
#
# The compiler stays external: no compiler internals are copied into
# mlx-omarchy, and nothing here builds from a local compiler checkout or a
# moving branch.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
# shellcheck source=/dev/null
source "$ROOT/ane-compiler.lock"

WORK_DIR="${MLX_OMARCHY_WORK_DIR:-$ROOT/.work}"
COMPILER_WORK="$WORK_DIR/ane-compiler"
ARCHIVE="$COMPILER_WORK/mil-hwx-compiler-$ANE_COMPILER_COMMIT.tar.gz"
SOURCE_DIR="$COMPILER_WORK/mil-hwx-compiler"
BIN_DIR="$COMPILER_WORK/bin"
WRAPPER="$BIN_DIR/mil-hwxc"

GNUSTEP_PREFIX="${GNUSTEP_PREFIX:-$HOME/.local/mil-hwx-gnustep}"

mkdir -p "$COMPILER_WORK"

download_archive() {
  if [[ ! -f "$ARCHIVE" ]]; then
    if ! curl --fail --location --retry 5 --retry-all-errors --retry-delay 10 \
        --output "$ARCHIVE" "$ANE_COMPILER_ARCHIVE_URL" \
        || [[ "$(head -c2 "$ARCHIVE" | od -An -tx1 | tr -d ' \n')" != "1f8b" ]]; then
      # Some hosts answer the anonymous asset URL with 404 while logged-in
      # fetches work; same immutable asset, same bytes, hash still enforced.
      rm -f "$ARCHIVE"
      command -v gh >/dev/null 2>&1 \
        || { echo "archive download failed: $ANE_COMPILER_ARCHIVE_URL" >&2; exit 1; }
      gh release download "$ANE_COMPILER_RELEASE_TAG" --repo "$ANE_COMPILER_REPOSITORY" \
        --pattern "$(basename "$ANE_COMPILER_ARCHIVE_URL")" --output "$ARCHIVE"
    fi
  fi
  # Fail fast on non-archive bytes (GitHub sometimes answers with a short
  # "404: Not Found" body while its archive cache is still cold).
  if [[ "$(head -c2 "$ARCHIVE" | od -An -tx1 | tr -d ' \n')" != "1f8b" ]]; then
    rm -f "$ARCHIVE"
    echo "downloaded file is not a gzip archive: $ANE_COMPILER_ARCHIVE_URL" >&2
    exit 1
  fi
}

# Rejects wrong bytes before anything is extracted or built.
verify_archive() {
  printf '%s  %s\n' "$ANE_COMPILER_ARCHIVE_SHA256" "$ARCHIVE" \
    | sha256sum --check --status || {
      echo "archive SHA-256 mismatch; refusing to build" >&2
      exit 1
    }
}

extract_archive() {
  local staging
  staging="$(mktemp -d "$COMPILER_WORK/.unpack.XXXXXX")"
  tar --extract --gzip --file "$ARCHIVE" --strip-components=1 \
    --directory "$staging"
  rm -rf "$SOURCE_DIR"
  mv "$staging" "$SOURCE_DIR"
}

ensure_toolchain() {
  if [[ -x "$GNUSTEP_PREFIX/bin/gnustep-config" ]]; then
    # Reuse an existing compatible install. The dependency pins live in the
    # locked source's scripts/bootstrap-linux-toolchain.sh (exact libobjc2,
    # gnustep-make, and gnustep-base commits, not moving branches).
    return
  fi
  GNUSTEP_BUILD_ROOT="$COMPILER_WORK/toolchain" \
    "$SOURCE_DIR/scripts/bootstrap-linux-toolchain.sh"
}

build_compiler() {
  local config="$GNUSTEP_PREFIX/bin/gnustep-config"
  export PATH="$GNUSTEP_PREFIX/bin:$PATH"
  export LD_LIBRARY_PATH="$GNUSTEP_PREFIX/lib${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}"
  export GNUSTEP_CONFIG_FILE="$GNUSTEP_PREFIX/etc/GNUstep/GNUstep.conf"
  make -C "$SOURCE_DIR" -B build/mil-hwxc \
    GNUSTEP_PREFIX="$GNUSTEP_PREFIX" GNUSTEP_CONFIG="$config"
  local links
  links=$(ldd "$SOURCE_DIR/build/mil-hwxc")
  [[ "$links" == *"$GNUSTEP_PREFIX/lib/libgnustep-base.so"* ]]
  [[ "$links" == *"$GNUSTEP_PREFIX/lib/libobjc.so"* ]]
}

run_host_tests() {
  # The compiler's own required host-side checks. Its `emit` mode is an
  # H16G smoke and is deliberately not treated as H13 evidence; the H13
  # qualification lives in scripts/verify-ane-compiler.sh.
  "$SOURCE_DIR/scripts/verify-linux-compiler.sh" software-tests
  "$SOURCE_DIR/scripts/verify-linux-compiler.sh" hygiene
}

install_wrapper() {
  mkdir -p "$BIN_DIR"
  cat > "$WRAPPER" <<EOF
#!/usr/bin/env bash
# Generated by scripts/prepare-ane-compiler.sh; do not edit.
prefix="$GNUSTEP_PREFIX"
export PATH="\$prefix/bin:\$PATH"
export LD_LIBRARY_PATH="\$prefix/lib\${LD_LIBRARY_PATH:+:\$LD_LIBRARY_PATH}"
export GNUSTEP_CONFIG_FILE="\$prefix/etc/GNUstep/GNUstep.conf"
exec "$SOURCE_DIR/build/mil-hwxc" "\$@"
EOF
  chmod +x "$WRAPPER"
}

print_provenance() {
  local binary_sha
  binary_sha=$(sha256sum "$SOURCE_DIR/build/mil-hwxc" | cut -d' ' -f1)
  local archive_sha
  archive_sha=$(sha256sum "$ARCHIVE" | cut -d' ' -f1)
  local pins
  pins=$(grep -E '^(objc|make|base)_commit=' "$SOURCE_DIR/scripts/bootstrap-linux-toolchain.sh" | tr '\n' ' ')
  cat <<EOF

compiler provenance
  repository:            $ANE_COMPILER_REPOSITORY
  commit:                $ANE_COMPILER_COMMIT
  archive URL:           $ANE_COMPILER_ARCHIVE_URL
  archive SHA-256:       $archive_sha
  package schema:        $ANE_COMPILER_PACKAGE_SCHEMA
  qualified target:      $ANE_COMPILER_QUALIFIED_TARGET
  gnustep prefix:        $GNUSTEP_PREFIX
  toolchain pins:        $pins
  binary:                $WRAPPER
  binary SHA-256:        $binary_sha
  host tests:            software-tests, hygiene (scripts/verify-linux-compiler.sh)
EOF
}

download_archive
verify_archive
extract_archive
ensure_toolchain
build_compiler
run_host_tests
install_wrapper
print_provenance
printf 'prepare-ane-compiler: PASS\n'
